### PR TITLE
One blst library to rule them all

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

Yesterday, blst released a new version which will automatically use optimized code paths in the portable build.

* https://github.com/supranational/blst/releases/tag/v0.3.11

This allows us to remove a good chunk of complexity. This PR will:

* Load the (one & only) native library built for the platform.
* Remove logs about which version of blst was loaded.
* Remove logic that checks if the optimized version is supported.
* Remove the two `CpuInfo` classes for querying info about the processor.

This PR depends on a new `jblst` release with these:

* https://github.com/Consensys/jblst/pull/40
* https://github.com/Consensys/jblst/pull/42

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
> This PR depends on a new `jblst` release with these:
> 
> * [Upgrade blst to v0.3.11 jblst#40](https://github.com/Consensys/jblst/pull/40)
> * [Only do portable builds jblst#42](https://github.com/Consensys/jblst/pull/42)


might be worth updating versions.gradle to match?

**Comment by jtraglia** [comment]
> might be worth updating versions.gradle to match?

Yes, but we need to make a new jblst release first 😅

**Comment by rolfyone** [comment]
> Yes, but we need to make a new jblst release first 😅

oh! fair :)

**Comment by StefanBratanov** [comment]
I will look into making a release. :) Can keep this draft here for the time being.

**Comment by StefanBratanov** [comment]
Released a new jblst version based on @jtraglia PRs: https://github.com/Consensys/jblst/releases/tag/0.3.11

**Comment by StefanBratanov** [comment]
@jtraglia Just as an update, we are testing this PR on one of our goerli nodes and all seems ok. I suppose we can mark it ready for review. I am not sure if you or someone else have done more testing on the runtime detection in blst?

**Comment by StefanBratanov** [comment]
Might be worth also adding in changelog that `JAVA_OPTS="-Dteku.portableBlst=true"` would no longer be required since there is a runtime detection available.

**Comment by jtraglia** [comment]
Hey @StefanBratanov. Good spot, I'll make that change.

I think I'd like to leave this PR open until next week so myself & others can do extra testing.

**Comment by StefanBratanov** [comment]
> Hey @StefanBratanov. Good spot, I'll make that change.
> 
> I think I'd like to leave this PR open until next week so myself & others can do extra testing.

Great. Sounds good. Thanks.

**Comment by StefanBratanov** [comment]
Hi @jtraglia any update with testing?

**Review by StefanBratanov — APPROVED** [review]
LGTM

**Pull request merged**
