### PR TITLE
Unleash the pandas

### LINKED ISSUE #5231: Merge banner art 🐼
Apparently it is mandatory to have an ASCII-art banner depicting pandas to appear on the console at the point of the Merge.

We could coordinate with Besu around this. Meanwhile I'll stick a good-first-issue label on this and see if any ASCII art gurus out there want to immortalise their name.

Somewhere around [here](https://github.com/ConsenSys/teku/blob/91c03c1b323c9551286bd10332624e550868f7a3/infrastructure/logging/src/main/java/tech/pegasys/teku/infrastructure/logging/EventLogger.java#L172) might be a good starting point.

Definition of done:
  - An ASCII art banner involving pandas appears at the point when Teku confirms that the TTD has been reached on testnets and mainnet.
  - Everyone agrees that it's super cool.
  - It doesn't break anything.
  - Colour is optional but must respect the user's existing settings.

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Currently using the banner art from https://github.com/ConsenSys/teku/pull/5781/ 

Prints the panda when the first block with a non-default payload is successfully imported. Will only ever print once and records the fact that it printed on disk to be completely sure of that.

## Fixed Issue(s)
fixes #5231 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by ajsutton** [comment]
We may want to consider only printing the pandas if the merge block is imported within some reasonable period of when the block actually happened (ie not when you sync a historic chain).

**Comment by Nashatyrev** [comment]
Another panda option: 

### 100 chars width: 

Terminal preview: 
image

Source:
```                                                                                                    
                    /&@@@@#,                                                                        
               ,@%           (@*     ./%@@@@@@@@@@@@@/*                                             
             %&                 %@%,                     #@@*                                       
           /&                       ,(&@@@@@@@@@@@@@@@#,      #@*                                   
          %*                   /@@@@@@@@@@@@@@@@@@@@@@@@@@@@(    ,@(                                
         #/                *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,   /@.                             
        .@              *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.  .@*     /@@*.  ./@&*          
        #.            &@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*   @, %#            /@        
        %           @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*  ,@                .@.     
        (,        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                     #(    
        .@      (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.                    ,&   
         /(    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                      .#  
          @  ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%                       #. 
        ,@  /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&                        @ 
        &  %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                        @ 
       @  (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/                       & 
      &  *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                       @ 
     #*  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                     .@ 
     &  @@@@@@@@@#,       *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.                   &  
    &  *@@@@@,                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&                 @,  
   .&  @@@.                    #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@             /@    
   #. *@           @@@@@@,      @@@@@@@@@@@@@@@.         *@@@@@@@@@@@@@@@@@@@@@@@@@&       /@#      
   @              @%     .(     %@@@@@@@@@@@@                /@@@@@@@@@@@@@@@@@@@@@@. /#.           
  .&                 &@@  /     @@@@@@@@@@@%                    &@@@@@@@@@@@@@@@@@@@*  @            
  *#              ,&@@@@, .    .@@@@@@@@@@@      (, .&@@*         %@@@@@@@@@@@@@@@@@(  @            
  /(              .@@@@@       @@@@@@@@@@@,    .       &@@          @@@@@@@@@@@@@@@@#  @            
  &.                .%@#     .@@@@@@@@@@@@       .@@@&  &@#          &@@@@@@@@@@@@@@%  @            
  &                        .@@@@@@@@@@@@@@       @@@@@* ,@%           &@@@@@@@@@@@@@#  @            
  #,                     (@@@@@@@@@@@@@@@@     .@@@@@@@@@@             @@@@@@@@@@@@@/  @            
   @                    @@@@@@@@@@@@@@@@@@       #@@@@@@#              /@@@@@@@@@@@@. ,%            
   */                 .@@@@@@@#&@@@@@@@@@@%                             @@@@@@@@@@@&  %             
    @                (@@@@,        @@@@@@@@&                            @@@@@@@@@@@*  @             
    .&             /@@@@&           #@@@@@@@@                           @@@@@@@@@@&  &,             
     */  @@*.../@@@@% #@*            @@@@@@@@#                          @@@@@@@@@@  /(              
      (#  %@@@@@@@@@  (@&            @@@@@@@@@                         *@@@@@@@@@  ,%               
       *&  ,@@@@@@@%  @@@@.         @@@@@@@@@@&                        @@@@@@@@%  *%                
         @   %@@@@@&  &@@@@@    #@@@@@@@@@@@@@@,                      @@@@@@@@.  %/                 
          /&   &@@@@(   .    (   @@@@@@@@@@@&  @                     @@@@@@@(  .@                   
            #%   (@@@@&,  *@@@@.  &@@@@@@@@&  *@@.                 &@@@@@@*   @,                    
              (@    %@@@@@@@@@@@%    /&&/    #@@@@@#            %@@@@@@&    @/                      
                 @%    *@@@@@@@@@@@/      ,@@@@@@@@@@@@@@&     #@@@@#    #@.                        
                   .@@      %@@@@@@@@@@@#     *@@@@@@@@#              %@,                           
                .@@,              /@@@(            %@&            .@&                               
               @          %@@@@&                                   @                                
              @          @@@@@@@@@@@@                              @                                
             *(         @@@@@@@@@@@@,                           #  #.                               
             ,%        @@@@@@@@@@@@@@                          /&  /*                               
              @       (@@@@@@@@@@@@@@@                        /&&  /*                               
               @      @@@@@@@@@@@@@@@@@@%.                   %%&&  /,                               
                .&@  ,@@@@@@@@@@@@@@@@@@@@@@@#.           /&%&%&&  %.                               
                  @  (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(    .%%  @                                
                  @  #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&           &                                
                 /@  (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#           /#                                
               ,@    .@@@@@@@@@@@@@@@@@@@@@@@@&/.                  &                                
               &      %@@@@@@@@@@@@@@@@@@@@#                        @                               
              (*       /@@@@@@@@@@@@@@@@@@*                          &                              
              #,         (@@@@@@@@@@@@@@@@                        @  @                              
              ,/            *&@@@@@@@@@@@(                       #(  &                              
               @                  .,(%&&@(                      @*  &                               
                @,            .*/                                 .@                                
                  .%@@@%(,..       ..*(&@@@%               %@@&&@&                                  
                                             /&@@@@&&%#(.                       
```

### 80 chars width: 

Terminal preview: 
image

Source:
```
              .%@&%%&@&,                                                        
           ,@            @.,&@&(          /&@@,                                 
         ,%                    *%@@@@@@@@#*      &&                             
        %.               (@@@@@@@@@@@@@@@@@@@@@@/   ,@.                         
       /.            *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   #%         ,*.           
       &          .@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@%  *&   @*       %%       
      .(        (@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&  #@             @     
       %      *@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#                *(   
       &     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@,                 %  
        @  /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                  ./ 
       %  %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                   & 
      &  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.                  ,,
     #. %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                  .,
    .# /@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(                 (.
    @ .@@@@@@@@@#,./@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#                @ 
   *  @@@@&             @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@              @  
   @ .@@         ,.      #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@.         #(   
  .* @         @@, ,@     @@@@@@@@@@@          .@@@@@@@@@@@@@@@@@@@  @&@@%      
  %           (  ,&  #    @@@@@@@@@.               @@@@@@@@@@@@@@@@# /          
  @           ,(@@@( ,   ,@@@@@@@@*    ,* #@@        @@@@@@@@@@@@@@@ .,         
  @            %@@@      @@@@@@@@@    *  %  *@&       ,@@@@@@@@@@@@@ ./         
  &                    %@@@@@@@@@(     *@@@, @@         @@@@@@@@@@@@ ./         
  @                  @@@@@@@@@@@@/    *@@@@@.%@         ,@@@@@@@@@@& ,,         
  @                &@@@@@@@@@@@@@&     (@@@@@/           &@@@@@@@@@/ (          
   @              @@@@@.  &@@@@@@@*                      ,@@@@@@@@@  @          
   ..           ,@@@/       ,@@@@@@/                      @@@@@@@@% ,/          
    %  &     .@@@@@&         ,@@@@@@*                    ,@@@@@@@@  &           
     @  &@@@@@@@  @@         .@@@@@@@                    %@@@@@@@  @            
      #. ,@@@@@@ .@@@,      ,@@@@@@@@(                   @@@@@@&  @             
        &  %@@@@  &@@&    @@@@@@@@@@#@                  @@@@@@   %              
         /(  #@@@(    (@&  @@@@@@@@/ /@               %@@@@@.  @                
           (%   &@@@@@@@@@   *&@%.  /@@@@.         ,@@@@@%   @                  
              @/   *@@@@@@@@&.   *@@@@@@@@@@@@     @@@/   (&                    
               (&@#     (@@@@@@%      .&@@@@           %&                       
            %*       (@%                             /.                         
           &        @@@@@@@@@#                        (                         
           &       @@@@@@@@@@                      /  &                         
           @      &@@@@@@@@@@@                    ,&  @                         
           .#     @@@@@@@@@@@@@%                 #&&  @                         
             #@. #@@@@@@@@@@@@@@@@@@,          #%%%&  %                         
              *, &@@@@@@@@@@@@@@@@@@@@@@@@@@@&    .&  (                         
              (, @@@@@@@@@@@@@@@@@@@@@@@@@@@%        /                          
             @   &@@@@@@@@@@@@@@@@@@@@@@@%           %                          
            @     @@@@@@@@@@@@@@@@@                   (*                        
           ,*      @@@@@@@@@@@@@@@                     @                        
           ,*        %@@@@@@@@@@@*                   ( %                        
            &            *%@@@@@@,                  @  &                        
            .%                                       .%                         
               ,(((,          .*((@*          ,&&@@&*                           
```

**Review by rolfyone — COMMENTED** [review]
LGTM

**Review by rolfyone — APPROVED** [review]

**Comment by ajsutton** [comment]
image

**Comment by dapplion** [comment]
This is very late, but I'm very happy :heart: :panda_face:

**Comment by ajsutton** [comment]
You can't waste pandas on these lesser testnets you know... :)

**Pull request merged**
