### PR TITLE
tiny refactors for late block reorg

### PR DESCRIPTION
**Pull request by rolfyone**
ForkChoiceNotifier needed to be supplier because it wasn't intiialised from BeaconChainController.

Also renamed `newSlot` to `proposalSlot` in line with a previous change.

adjunct to #6595

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
oh no, initialization sequence forcing us to pass a `Supplier`.. maybe there is something better

**Comment by tbenr** [comment]
@rolfyone tried to remix the cards https://github.com/tbenr/teku/commit/640c078644d68141147b113ba7673708c369f082
WDYT?

**Comment by rolfyone** [comment]
> @rolfyone tried to remix the cards [tbenr@640c078](https://github.com/tbenr/teku/commit/640c078644d68141147b113ba7673708c369f082)
> WDYT?

looks worse? :/

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
