### PR TITLE
Add weighted participation metrics

### LINKED ISSUE #3134: Add a more accurate participation metric
Related: #2630 

We can currently estimate participation rate from `beacon_previous_live_validators` and `beacon_previous_active_validators`. However this is inaccurate due to both (1) the issue mentioned in #2630 (incorrect target votes), and (2) vote weighting by effective balance. We require 2/3 of _attesting balance_ for finalisation, not 2/3 of active validator count.

I propose adding `beacon_previous_participation_rate` and `beacon_current_participation_rate` metrics to supply the accurate measure.

### PR DESCRIPTION
**Pull request by cemozerr**
## PR Description
Add weighted participation metrics.

Left a comment as this metric seems pretty expensive from the CPU perspective. So not sure if it's a good idea to include it.

## Fixed Issue(s)

Fixes #3134

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

**Review by ajsutton — COMMENTED** [review]
This is repeating one of the most expensive parts of epoch transitions, so I think the performance concerns are valid. It does happen on a separate thread which helps but I'm still hesitant to merge this as is.  Ideally we would just capture this information when we process the epoch as part of importing blocks and report from there.  The challenge is how to handle fork changes but we could potentially use the state transition caches as a way to make this information more cheaply available.

**Comment by cemozerr** [comment]
@ajsutton The issue is, this metric, along with other BeaconChainMetrics, get calculated and updated every slot. So using the result during epoch processing would result us getting updates only once per epoch.

**Comment by ajsutton** [comment]
hmmm, having to do the major part of epoch transition every slot is going to be even worse than I thought then.

Validator effective balances only change once per epoch so we should still be able to cache key parts of this at epoch boundaries.

**Comment by cemozerr** [comment]
> hmmm, having to do the major part of epoch transition every slot is going to be even worse than I thought then.
> 
> Validator effective balances only change once per epoch so we should still be able to cache key parts of this at epoch boundaries.

I did cache the validator effective balances now but the part we look up the validator index from committee shuffling is still a pretty costly operation. Not sure how to proceed.

**Comment by ajsutton** [comment]
So this one's a bit stuck because of the performance impacts. We don't want to have to calculate the active validators, the list of balances or store an additional copy of those balances in memory.

But with #3352 the new `TotalBalances` object is the perfect information we'd need to calculate these metrics very cheaply.  Currently its not cached with the state and doesn't fit the normal `TransitionCaches` model well, but potentially we could create some way to either cache the value or only update the metrics when we actually process the state transition for the canonical state (not sure if updating them on reorg is important or not).

**Comment by cemozerr** [comment]
Closing this PR as there were 3 bug fixes made on the BeaconChainMetrics after this PR and it is too risky to build on top of this without losing those fixes. Will follow up with another PR for the same features.

**Pull request closed without merging**
