### PR TITLE
Bumping web3j to 4.9.8 (fixing Websockets bug)

### LINKED ISSUE #6563: `shouldPassMergeTransitionUsingWebsocketsEngine` breaking very often
The shouldPassMergeTransitionUsingWebsocketsEngine AT is breaking quite often currently, we need to have a look and see if there's an actual problem, or if its related to using `swift` now.

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
Originally making `shouldPassMergeTransitionUsingWebsocketsEngine` very flaky, but it's no more in FLAKY list and I've checked latest month manually, no single fail there. Anyway bumping to close the issue

## Fixed Issue(s)

Fixes #6563 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM, but i've also included this in the dependency updates sweep...

**Comment by StefanBratanov** [comment]
> LGTM, but i've also included this in the dependency updates sweep...

web3j update was not in your dependecy update commit, so guess can merge this one?

**Comment by zilm13** [comment]
@rolfyone it wasn't in #7043 
I've merged recent master and you could see, it's still a change in this PR

**Comment by rolfyone** [comment]
seems odd, but sure, lets merge i guess...

**Pull request merged**
