### PR TITLE
Update external signer block signing integration test

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Update external signer block signing integration test. Use parameterized test for Bellatrix and Capella block signing.
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
Are we planning on putting more tests in? i don't see why we'd do this restructuring currently...

i'd probably prefer its an abstract base class and we don't have to do `data.` everywhere like the `AbstractDataBackedIntegrationTest`  as a concrete example...

**Comment by usmansaleem** [comment]
@rolfyone The primary intention is to use parameterized test for bellatrix, capella and onward specs for blocksigning.

**Comment by rolfyone** [comment]
Have a quick look at 
```
  @ParameterizedTest
  @MethodSource("allNetworksWithAllMilestones")
```
And make sure, but I think you're better off not breaking all of that information out potentially...

**Comment by usmansaleem** [comment]
Closing, will open a new PR with consolidated integration test for external signer.

**Pull request closed without merging**
