### PR TITLE
Use thread local `MessageDigest`s for hashing functions

### PR DESCRIPTION
**Pull request by tbenr**
There are still several codepath pointing to sha256 hash functions. As per my previous ssz optimizations I saw that instantiating every time a new `MessageDigest` is quite expensive. `MessageDigest` reset themself everytime `digest()` is called, so they are reusable.

I'd like to see if there are noticable benefits with this approach.

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by StefanBratanov — APPROVED** [review]
makes sense to me

**Comment by tbenr** [comment]
`Old`
```
Benchmark                             Mode  Cnt        Score        Error  Units
Sha256Benchmark.pureKeccak256        thrpt   50  2866031.990 ±  48965.282  ops/s
Sha256Benchmark.pureSha256           thrpt   50  2926474.482 ±  31450.630  ops/s
Sha256Benchmark.sha256of33byteArray  thrpt   50  2857816.612 ±  23948.549  ops/s
Sha256Benchmark.sha256of33bytes      thrpt   50  2718669.114 ± 119768.117  ops/s
```

`New`
```
Benchmark                             Mode  Cnt        Score        Error  Units
Sha256Benchmark.pureKeccak256        thrpt   50  3347330.321 ± 141670.181  ops/s
Sha256Benchmark.pureSha256           thrpt   50  3069017.952 ±  28841.554  ops/s
Sha256Benchmark.sha256of33byteArray  thrpt   50  3097595.629 ±  32631.950  ops/s
Sha256Benchmark.sha256of33bytes      thrpt   50  3067835.616 ±  35049.572  ops/s
```

**Comment by StefanBratanov** [comment]
> `Old`
> 
> ```
> Benchmark                             Mode  Cnt        Score        Error  Units
> Sha256Benchmark.pureKeccak256        thrpt   50  2866031.990 ±  48965.282  ops/s
> Sha256Benchmark.pureSha256           thrpt   50  2926474.482 ±  31450.630  ops/s
> Sha256Benchmark.sha256of33byteArray  thrpt   50  2857816.612 ±  23948.549  ops/s
> Sha256Benchmark.sha256of33bytes      thrpt   50  2718669.114 ± 119768.117  ops/s
> ```
> 
> `New`
> 
> ```
> Benchmark                             Mode  Cnt        Score        Error  Units
> Sha256Benchmark.pureKeccak256        thrpt   50  3347330.321 ± 141670.181  ops/s
> Sha256Benchmark.pureSha256           thrpt   50  3069017.952 ±  28841.554  ops/s
> Sha256Benchmark.sha256of33byteArray  thrpt   50  3097595.629 ±  32631.950  ops/s
> Sha256Benchmark.sha256of33bytes      thrpt   50  3067835.616 ±  35049.572  ops/s
> ```

Nice. Looks better.

**Comment by tbenr** [comment]
10milion rounds

memory allocations:

old
image

new
image

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
