### PR TITLE
Update Besu dependencies

### LINKED ISSUE #8327: Update Besu metrics dependencies
Initial draft work: https://github.com/Consensys/teku/pull/8288

**Steps**

- [x] Finally upgrade `io.prometheus:simpleclient` from `0.9.0` to `0.16.0`
- [x] Upgrade besu dependencies from `24.1.2` to `24.5.2`
- [x] Fix tests
- [x] Ensure metrics/dashboards are not broken
- [x] Update metrics to comply with naming standard for counters introduced in v0.10 of `io.prometheus:simpleclient`
- [ ] Add breaking changing announcement in the changelog

This ticket can be close when all the following are done:

- [x] Dashboards have been updated 
- [x] Release new dashboard (backwards compatible)
- [x] Breaking changes announcement for next release is done - PR #8361 
- [ ] Docs PR adding a page with all metrics updated - Branch [here](https://github.com/gfukushima/doc.teku/tree/metrics-update)
- [ ] PR #8288 is merged into master after release 24.6.0

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Besu upgraded from 0.9.0 version few months back - https://github.com/hyperledger/besu/pull/6422 so can upgrade our version as well.

Leaving as draft because of following Besu changelog in release https://github.com/hyperledger/besu/releases/tag/24.3.0:

> Following the OpenMetrics convention, the updated Prometheus client adds the _total suffix to every metrics of type counter, with the effect that some existing metrics have been renamed to have this suffix. If you are using the official Besu Grafana dashboard [(available here)](https://grafana.com/grafana/dashboards/16455-besu-full/), just update it to the latest revision, that accepts the old and the new name of the affected metrics. If you have a custom dashboard or use the metrics in other ways, then you need to manually update it to support the new naming.

## Fixed Issue(s)
Fixes #8327 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by gfukushima** [comment]
I've fixed the tests and am comparing to the current stable version to check which metrics we should adjust in the dashboard, since the new version adds suffix to some types by default. Please don't merge this until further notice.

**Comment by gfukushima** [comment]
This is now ready for merge.

**Review by StefanBratanov — COMMENTED** [review]
LGTM, I would just change the CHANGELOG - move the metrics stuff from Upcoming Breaking Changes to Breaking Changes

**Comment by gfukushima** [comment]
I've cleared the change logs and have added an entry for breaking changes. The announcements were for the previous release.

**Review by lucassaldanha — APPROVED** [review]

**Pull request merged**
