### PR TITLE
[Java API] Allow to customize `BeaconChainController` construction 

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

This is the follow PR up to #4601 

Currently Teku is pretty solid in terms of substituting/tweaking various components. 
Trying to address this, the initial change I'd like to discuss is to make `BeaconChainController` construction more customizable. 

- Add `BeaconChainControllerFactory` to the `TekuConfiguration`
- Make `BeaconChainController` extensible with making all its members protected. 

I guess the latter change is a bit controversial to common Teku patterns. I.e. altering behavior via inheritance is generally not too good practice. 

However overriding specific `BeaconChainController` methods looks like the easiest way to tweak the logic and replace components without much support burden for Teku maintainers and without duplicating a lot of code for Teku clients 

Java API is not official and declared as unstable so Teku would still not provide any guarantees that overridden client `BeaconChainController` is not broken after any commit. 

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by ajsutton** [comment]
I don't think I can express how much I hate the current `BeaconChainController`. It's this huge builder thing that lives on beyond the initial build and does way, way too much.

Given we're not committing to keeping this api unchanged, I'm ok with this as a quick fix type of thing, but I do wonder if we should be more radical and create an actual builder for all the init stuff that `BeaconChainController`. I'm not really sure what that would look like exactly though as there are some important timing elements with some things being created before `RecentChainData` is initialised, some only after the `Store` is available, some only after genesis etc. It feels a bit like ProtocolSpecBuilder (https://github.com/hyperledger/besu/blob/93b556aa9de4c9b9b758ba12390f232a3c7510be/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java) in Besu but with so many things being created it could wind up being an awful lot of boilerplate code and I'm not sure if that's the right approach or not.

**Comment by Nashatyrev** [comment]
Yep the class is huge but it assembles a lot of components with a lot of non-trivial inter-dependencies so probably we should deal with it as an inevitable evil and treat it just as an assembling 'script' code. 
I was thinking about creating a `BeaconChainController` builder or decomposing it in some way but it doesn't seem to add much value while adds another bunch of boilerplate code and a burden of maintaining it.

**Comment by Nashatyrev** [comment]
Also added Javadoc with caution about unstable API

**Review by ajsutton — APPROVED** [review]
LGTM.  I guess in terms of cleaning up `BeaconChainController` we probably want to eventually make it be the "builder" (though probably not exactly a classic builder pattern) and just make sure we move any business logic out of it. It doesn't have much business logic left, but there's a few things like the `onTick` method and probably some other stuff scattered through it that could be separated out.

**Pull request merged**
