### PR TITLE
added a sleep while doing large bls batches

### PR DESCRIPTION
**Pull request by rolfyone**
## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
basically we were adding way too many signatures over a 20k batch, and overflowing buffers... this is a low tech solution which I used for network updates.

**Comment by lucassaldanha** [comment]
I'd rather have a limit on the number of BlsToExecutionChanges operations we can receive via a single API request. I think this idea of throttling the inclusion on the API side adds unnecessary complexity to our API layer.

**Comment by tbenr** [comment]
I'm with Lucas here.. forcing user to split in multiple calls seems better. I guess there is no `limit` mention in API spec but in this particular case I don't think it's a big deal to have some "client diversity".

PS: `Thread.sleep` in production code is difficult to accept :)

**Comment by rolfyone** [comment]
well the sleeps are machine dependent as to the size, but the main point of this was we were getting 500 errors on the api, which is way worse... and I didnt want to lose track of it.

We can put in a limit, our queue limit is 10k, and i don't have 10k to test with now but hopefully that won't overflow the signing queue again...

**Comment by rolfyone** [comment]
raised #7601

**Pull request closed without merging**
