### PR TITLE
Fix signature verification on fork boundaries

### LINKED ISSUE #6951: Produced invalid aggregate signature on milestone activation with head still on previous milestone
This happened on last Goerli upgrade to Capella

```text
{"@timestamp":"2023-03-14T22:25:36,008","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Milestone   *** Epoch: 162304, Activating network upgrade: CAPELLA","throwable":""}
{"@timestamp":"2023-03-14T22:25:36,008","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Epoch Event *** Epoch: 162304, Justified checkpoint: 162303, Finalized checkpoint: 162302, Finalized root: 59738387e8be4fdbaac9ca07ae39c214414ad145bd81e7fe6b3b6ecf6c639696","throwable":""}
{"@timestamp":"2023-03-14T22:25:37,450","level":"WARN","thread":"CombinedStorageChannel-0","class":"teku-db-log","message":"DB operation: "Transaction Commit" took too long: 127 milliseconds. The alert threshold is set to: 20 milliseconds","throwable":""}
{"@timestamp":"2023-03-14T22:25:37,456","level":"WARN","thread":"CombinedStorageChannel-0","class":"teku-db-log","message":"DB operation: "Block Import" took too long: 1172 milliseconds. The alert threshold is set to: 20 milliseconds","throwable":""}
{"@timestamp":"2023-03-14T22:25:37,618","level":"INFO","thread":"SlotEventsChannel-10","class":"teku-status-log","message":"Attestation performance: epoch 162302, expected 5000, produced 5000, included 5000 (100%), distance 1 / 1.25 / 7, correct target 4826 (97%), correct head 4826 (97%)","throwable":""}
{"@timestamp":"2023-03-14T22:25:37,618","level":"INFO","thread":"SlotEventsChannel-10","class":"teku-status-log","message":"Block performance: epoch 162303, expected 2, produced 2, included 2 (100%)","throwable":""}
{"@timestamp":"2023-03-14T22:25:37,640","level":"INFO","thread":"beaconchain-async-4","class":"teku-status-log","message":"Sync committee performance: epoch 162303, expected 256, produced 256, correct 256, included 176 (69%)","throwable":""}
{"@timestamp":"2023-03-14T22:25:40,006","level":"INFO","thread":"validator-async-7","class":"teku-validator-log","message":"Validator   *** Published sync_signature     Count: 4, Slot: 5193728, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:25:40,138","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Slot Event  *** Slot: 5193728, Block:                                                        ... empty, Justified: 162303, Finalized: 162302, Peers: 99","throwable":""}
{"@timestamp":"2023-03-14T22:25:40,655","level":"INFO","thread":"validator-async-5","class":"teku-validator-log","message":"Validator   *** Published attestation        Count: 163, Slot: 5193728, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,095","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,095","level":"ERROR","thread":"beaconchain-async-4","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,097","level":"ERROR","thread":"beaconchain-async-6","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,099","level":"ERROR","thread":"beaconchain-async-7","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,100","level":"ERROR","thread":"beaconchain-async-5","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,101","level":"ERROR","thread":"beaconchain-async-3","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,102","level":"ERROR","thread":"beaconchain-async-0","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,103","level":"ERROR","thread":"beaconchain-async-2","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,104","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,105","level":"ERROR","thread":"beaconchain-async-4","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,105","level":"ERROR","thread":"beaconchain-async-6","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193728: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:44,108","level":"ERROR","thread":"validator-async-7","class":"teku-validator-log","message":"Validator   *** Failed to produce aggregate  Slot: 5193728 Validator: b830777, 906e958, 9823491, 957a545, 89ba565, 8890a2f, abbdf98, ad1004f, 917a4da, a817b43, 9330dcb","throwable":" tech.pegasys.teku.validator.client.duties.RestApiReportedException: Rejecting aggregate with invalid batch signature\n"}
{"@timestamp":"2023-03-14T22:25:52,053","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Slot Event  *** Slot: 5193729, Block:                                                        ... empty, Justified: 162303, Finalized: 162302, Peers: 100","throwable":""}
{"@timestamp":"2023-03-14T22:25:52,274","level":"INFO","thread":"validator-async-5","class":"teku-validator-log","message":"Validator   *** Published sync_signature     Count: 4, Slot: 5193729, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:25:52,394","level":"INFO","thread":"validator-async-1","class":"teku-validator-log","message":"Validator   *** Published attestation        Count: 157, Slot: 5193729, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,328","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,339","level":"ERROR","thread":"beaconchain-async-6","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,344","level":"ERROR","thread":"beaconchain-async-2","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,351","level":"ERROR","thread":"beaconchain-async-5","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,356","level":"ERROR","thread":"beaconchain-async-0","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,361","level":"ERROR","thread":"beaconchain-async-4","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,366","level":"ERROR","thread":"beaconchain-async-7","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,370","level":"ERROR","thread":"beaconchain-async-3","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,376","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193729: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:25:56,376","level":"ERROR","thread":"validator-async-2","class":"teku-validator-log","message":"Validator   *** Failed to produce aggregate  Slot: 5193729 Validator: b017966, a3dea9a, 98864fa, 8300a13, ae68d68, 84365d6, af98dc4, 859f403, 8b4b9b0","throwable":" tech.pegasys.teku.validator.client.duties.RestApiReportedException: Rejecting aggregate with invalid batch signature\n"}
{"@timestamp":"2023-03-14T22:26:04,004","level":"INFO","thread":"validator-async-2","class":"teku-validator-log","message":"Validator   *** Published sync_signature     Count: 4, Slot: 5193730, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:26:04,043","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Slot Event  *** Slot: 5193730, Block:                                                        ... empty, Justified: 162303, Finalized: 162302, Peers: 99","throwable":""}
{"@timestamp":"2023-03-14T22:26:04,344","level":"INFO","thread":"validator-async-0","class":"teku-validator-log","message":"Validator   *** Published attestation        Count: 168, Slot: 5193730, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,019","level":"ERROR","thread":"beaconchain-async-3","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,019","level":"ERROR","thread":"beaconchain-async-2","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,023","level":"ERROR","thread":"beaconchain-async-5","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,025","level":"ERROR","thread":"beaconchain-async-6","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,026","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,027","level":"ERROR","thread":"beaconchain-async-0","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,029","level":"ERROR","thread":"beaconchain-async-7","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193730: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:08,029","level":"ERROR","thread":"validator-async-2","class":"teku-validator-log","message":"Validator   *** Failed to produce aggregate  Slot: 5193730 Validator: a8ccc55, a917f06, b6b6da7, 999924b, a480bfb, 884001d, a7c26a9","throwable":" tech.pegasys.teku.validator.client.duties.RestApiReportedException: Rejecting aggregate with invalid batch signature\n"}
{"@timestamp":"2023-03-14T22:26:16,044","level":"INFO","thread":"TimeTick-1","class":"teku-event-log","message":"Slot Event  *** Slot: 5193731, Block:                                                        ... empty, Justified: 162303, Finalized: 162302, Peers: 100","throwable":""}
{"@timestamp":"2023-03-14T22:26:16,266","level":"INFO","thread":"validator-async-6","class":"teku-validator-log","message":"Validator   *** Published sync_signature     Count: 4, Slot: 5193731, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:26:16,355","level":"INFO","thread":"validator-async-4","class":"teku-validator-log","message":"Validator   *** Published attestation        Count: 169, Slot: 5193731, Root: 6a7ac459f234540c9975e4eb98049dd3bde33141246916b9f446b7f98e17af3b","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,025","level":"ERROR","thread":"beaconchain-async-0","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,025","level":"ERROR","thread":"beaconchain-async-3","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,031","level":"ERROR","thread":"beaconchain-async-7","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,033","level":"ERROR","thread":"beaconchain-async-6","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,034","level":"ERROR","thread":"beaconchain-async-4","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,036","level":"ERROR","thread":"beaconchain-async-1","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,037","level":"ERROR","thread":"beaconchain-async-2","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,038","level":"ERROR","thread":"beaconchain-async-5","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,040","level":"ERROR","thread":"beaconchain-async-0","class":"teku-validator-log","message":"Validator   *** Produced invalid aggregate for slot 5193731: Rejecting aggregate with invalid batch signature","throwable":""}
{"@timestamp":"2023-03-14T22:26:20,040","level":"ERROR","thread":"validator-async-6","class":"teku-validator-log","message":"Validator   *** Failed to produce aggregate  Slot: 5193731 Validator: 8d19aab, 817533b, a0766b0, 8f9c497, a0f6d43, a93a171, ac234fb, a4625f3, 8417aed","throwable":" tech.pegasys.teku.val
idator.client.duties.RestApiReportedException: Rejecting aggregate with invalid batch signature\n"}
```

### PR DESCRIPTION
**Pull request by tbenr**
fixes signature validation on `AggregateAttestation` and `SignedContributionAndProofValidator` when our current slot is in Milestone `B` and our head is still on Milestone `A`.

fixes #6951 

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
Makes sense to me, essentially the state was not updated because of the missing blocks in the beginning of the fork? So it's more reliable to use the fork info based on the slot of the object that needs to be signed

**Comment by tbenr** [comment]
yes.. I think there were some inconsistency during signature verification. I think that `ForkInfo` should be always be derived from the slot taken from the object we are validating and not from our head\state.
The should only be used to get the genesis validator root.

**Comment by zilm13** [comment]
Looks great!
Just one question, how did we pass https://github.com/ConsenSys/teku/blob/06efe1053107e5f09030dc5d2fc1ef6e5ed47623/ethereum/statetransition/src/integration-test/java/tech/pegasys/teku/statetransition/attestation/AttestationManagerIntegrationTest.java#L183 before this?
So, `SignedContributionAndProofValidator` is tested for changes, it would be good to test `AggregateAttestationValidator` changes too

**Comment by tbenr** [comment]
> Just one question, how did we pass

because attestation wasn't affected! only Attestation aggregation and sync contributions were rejected.

worth to add integration tests for them...

**Review by mehdi-aouadi — APPROVED** [review]
Makes sense and LGTM

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
