### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by mehdi-aouadi**
## PR Description
Dependencies update

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
It seems like swagger UI updated its major version. It would be worth starting a node locally and testing out swagger works as expected.

**Comment by mehdi-aouadi** [comment]
> It seems like swagger UI updated its major version. It would be worth starting a node locally and testing out swagger works as expected.

Yep did that already. Swagger looked working fine locally 🚀
Would be cool if you try it too to be sure 🙏

**Comment by zilm13** [comment]
2 questions:
- Will we ignore RocksDB updates forever? Maybe add some comment there?
- It shows javalin 5.6.1 is available for me

**Review by zilm13 — APPROVED** [review]
LGTM

**Comment by mehdi-aouadi** [comment]
> 2 questions:
> 
> * Will we ignore RocksDB updates forever? Maybe add some comment there?
> * It shows javalin 5.6.1 is available for me

Regarding javalin 5.6.1, [javalin-rendering](https://github.com/javalin/javalin-rendering/tags) 5.6.1 is not published yet. Since we're grouping the javalin dependencies it would break unless we ungroup javalin core and rendering (which doesn't seem to be the best solution). So I preferred to update it once the rendering lib is published.

Regarding Rocksdb, since we didn't update it for a while, I thought a separate update would be better to evaluate its impact. Plus the last time we downgraded from 7.9.2 back to 7.7.3, so I think it's worth being more careful about it

**Comment by zilm13** [comment]
@mehdi-aouadi added comment there about RocksDB https://github.com/Consensys/teku/issues/6943#issuecomment-1629069947
Not sure it's an appropriate place but anyway

**Comment by mehdi-aouadi** [comment]
> @mehdi-aouadi added comment there about RocksDB [#6943 (comment)](https://github.com/Consensys/teku/issues/6943#issuecomment-1629069947)
> Not sure it's an appropriate place but anyway

Cool thanks! I was thinking I'd suggest to create an internal issue, didn't know we already had a spike about it... Good to know

**Comment by StefanBratanov** [comment]
> > It seems like swagger UI updated its major version. It would be worth starting a node locally and testing out swagger works as expected.
> 
> Yep did that already. Swagger looked working fine locally 🚀 Would be cool if you try it too to be sure 🙏

Tested locally as well against your branch. Confirmed swagger looks good

**Pull request merged**
