### PR TITLE
Fixed store passing its locks about

### PR DESCRIPTION
**Pull request by rolfyone**
Noticed this issue in the deadlock PR, but there was no appetite to fix in that, so i've raised a PR to encapsulate the issue and fix.

We shouldn't be passing locks around, and I'd like this issue fixed so here's the proposed solution from #7756

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by zilm13** [comment]
You are not using lock while using blockProvider, you are using it only when setting it up and freeing immediately. Restore deleted test, add the same setup you made in Store, and you'll see it

**Comment by rolfyone** [comment]
the test is the only usage outside the constructor. pushed a change that should make it cleaner.

**Comment by zilm13** [comment]
Looks good to me, I'd just like to see test back but new BlockProvider is deep in Store, it would be ugly and complex to test it.

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
