### PR TITLE
Reduce lock contention in CacheableTaskQueue

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
To ensure a smoother flow of tasks through `CacheableTaskQueue` and minimise the length of time the cache lock is held, start task execution and complete task futures via an `AsyncRunner`.

## Fixed Issue(s)
Originally thought this would help with #2661 but it does not.  Still a good change to make.

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

### CODE REVIEW

**Review by Nashatyrev — APPROVED** [review]
LGTM

Just a general comment: do we really want another asynchrony level here? May be it would be enough just to make locks finer grained (i.e. execute and complete tasks outside lock)?

**Comment by Nashatyrev** [comment]
Also a question not related to the changes: why are we using `Lock` instead of `synchronized`? The latter seems less verbose and error-prone. Also it tends to be faster in general scenario if I'm not mistaken

**Comment by Nashatyrev** [comment]
BTW fun fact from my practice: `ReentrantLock.unlock()` call can fail to execute in the `finally` section: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8046936
So much time was spent hunting this bug in my production code 🤒

**Comment by ajsutton** [comment]
The description is probably a bit misleading here and puts too much focus on locks.  The key issue is that when `CacheableTaskQueue` starts processing a task or completes the future, that triggers some unknown amount of work before the call returns.  When that happens inside the lock there's no chance `CacheableTaskQueue` will be able to start another task or deal with a result being available, but even without the lock, it likely delays starting the next task when one finishes unnecessarily because the chained actions from the future are all completing on the same thread that will then go on to start the next task.

By starting and finishing tasks via the thread pool, it guarantees that the next task can start straight away.

> Also a question not related to the changes: why are we using `Lock` instead of `synchronized`? The latter seems less verbose and error-prone. Also it tends to be faster in general scenario if I'm not mistaken

In earlier versions of this class, the locks were only held for part of the methods and then released.  I think at one point I expected it to use read/write locks. But you're right, it would be better to just use `synchronized` here.

**Pull request merged**
