### PR TITLE
Expose single blob kzg proof verification method in KZG interface

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Single blob kzg proof verification would be required for gossip validation as per https://github.com/ethereum/consensus-specs/pull/3531

## Fixed Issue(s)
N/A

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
can you use this in `MiscHelpersDeneb::verifyBlobSidecar` already?

**Comment by tbenr** [comment]
ah but that's gone now.. was on a old branch

**Review by zilm13 — APPROVED** [review]
LGTM

**Comment by StefanBratanov** [comment]
Actually I did bit of refactoring, but not sure about it. In my mind is cleaner, having `verifyBlobKzgProof` and `verifyBlobKzgProofBatch` both in MiscHelpers. Also created an abstract class for the validating proxy to be used for byRoot PR. Let me know @zilm13 if you like it or I am happy to revert my last two commits as well.

**Comment by zilm13** [comment]
Merge it, i'm ok
abstract class will not fit in my code, but let's resolve it in another place

**Comment by StefanBratanov** [comment]
> Merge it, i'm ok abstract class will not fit in my code, but let's resolve it in another place

KK. Should be ok though can just use extends `AbstractBlobSidecarsValidatingProxy` and that exposes the kzg verificiation method

**Comment by zilm13** [comment]
I need to use it without instance also
I will think out how to do this after could merge your PR https://github.com/Consensys/teku/blob/979c6cfa45651ca563b4ba78bac5cc3f46626521/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/peers/DefaultEth2Peer.java#L278-L299

**Comment by zilm13** [comment]
actually i think i'll make an instance for this case too to keep logging

**Comment by StefanBratanov** [comment]
> actually i think i'll make an instance for this case too to keep logging

Cool. Let me know when you finish the PR. I will have a look.

**Pull request merged**
