### PR TITLE
re-instate the ignore rule for seen aggregates.

### LINKED ISSUE #4721: Reapply ignore rule for seen aggregates
### Description
Re-add the ignore validation rule that was removed by https://github.com/ethereum/consensus-specs/issues/2183#issuecomment-981232838

### PR DESCRIPTION
**Pull request by rolfyone**
fixes #4721

Signed-off-by: Paul Harris <paul.harris@consensys.net>

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by ajsutton — COMMENTED** [review]
I think we should remove the `aggregateAttestationResultCache` from `AggregateAttestationValidator` now as well. We'll automatically ignore aggregates containing the same attestation so this cache won't ever save work anymore.

But otherwise looks good.

**Comment by ajsutton** [comment]
The other piece to remove is `processedAggregateAttestations` in `AttestationManager`.  The validator will ignore duplicate attestations again so we don't need to do it in `AttestationManager`.

**Comment by rolfyone** [comment]
ready for re-review

**Review by ajsutton — APPROVED** [review]
LGTM.

**Pull request merged**
