### PR TITLE
Add LUKSO Mainnet configs and files

### LINKED ISSUE #7381: Add LUKSO Mainnet to Teku
### Description
We need to add LUKSO Mainnet configuration and files to `Teku` core implementation. This is `web3signer` requirement to support LUKSO Mainnet network.

### PR DESCRIPTION
**Pull request by mxmar**
## PR Description

We are in need to add LUKSO Mainnet chain configuration files to `Teku` core implementation. This is because we are going to integrate `web3signer` and we have feedback from `Teku` team (w3s) that we need to prepare LUKSO Mainnet PR against `Teku`.

## Fixed Issue(s)

fixes #7381

## Documentation

- [X] No changes in documentation

## Changelog

- [X] Added LUKSO Mainnet configuration

### CODE REVIEW

**Comment by mxmar** [comment]
We have built `Teku` successfully from feature branch, but when we are running binary, we see:
```sh
17:17:26.380 INFO  - Loading deposit tree snapshot from jar:file:/home/sw/projects/teku/build/install/teku/lib/teku-services-powchain-develop.jar!/tech/pegasys/teku/services/powchain/lukso.ssz
Teku failed to start: tech.pegasys.teku.infrastructure.ssz.sos.SszDeserializeException: First variable element offset doesn't match the end of fixed part
```

**Comment by StefanBratanov** [comment]
> We have built `Teku` successfully from feature branch, but when we are running binary, we see:
> 
> ```shell
> 17:17:26.380 INFO  - Loading deposit tree snapshot from jar:file:/home/sw/projects/teku/build/install/teku/lib/teku-services-powchain-develop.jar!/tech/pegasys/teku/services/powchain/lukso.ssz
> Teku failed to start: tech.pegasys.teku.infrastructure.ssz.sos.SszDeserializeException: First variable element offset doesn't match the end of fixed part
> ```

Hi, you can replicate this failure by running `DepositSnapshotsBundleTest`. It appers that the lukso.ssz is not correct. How did you generate it? Generally, you would download it from a running node, sth like:
```
curl -s --show-error --fail -H 'Accept: application/octet-stream' http://localhost:5051/eth/v1/beacon/deposit_snapshot -o "lukso.ssz" >&2
```

**Comment by StefanBratanov** [comment]
Also, need to run `./gradlew spotlessApply` to fix some formatting issues. Otherwise, PR looks good. :) Thanks.

**Comment by mxmar** [comment]
> Also, need to run `./gradlew spotlessApply` to fix some formatting issues. Otherwise, PR looks good. :) Thanks.

Yes, you are right, thanks :) I did it now :) So the only thing is to verify `lukso.ssz` on our side. For `ssz` we have our own generator - https://github.com/lukso-network/tools-lodestar-genesis-ssz-generator at launch time that was the only generator able to generate genesis beacon state based on `deposit_data.json` and able to create bellatrix genesis beacon state.

**Comment by StefanBratanov** [comment]
> > Also, need to run `./gradlew spotlessApply` to fix some formatting issues. Otherwise, PR looks good. :) Thanks.
> 
> Yes, you are right, thanks :) I did it now :) So the only thing is to verify `lukso.ssz` on our side. For `ssz` we have our own generator - https://github.com/lukso-network/tools-lodestar-genesis-ssz-generator at launch time that was the only generator able to generate genesis beacon state based on `deposit_data.json` and able to create bellatrix genesis beacon state.

lukso-genesis.ssz is ok. The `lukso.ssz` is based on deposit tree snapshot and can be retrieved from the beacon API: https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getDepositSnapshot It helps with loading deposits faster on startup.

**Comment by StefanBratanov** [comment]
Also, can you please update also the CHANGELOG.md under Additions and improvements. Would be good to add in next release notes. Something like the announcement below should suffice.
```
Add support for [Lukso network](https://lukso.network/) `--network=lukso`
```

**Comment by StefanBratanov** [comment]
New file looks good! :) Only thing left for the unit tests to pass is adding lukso to the CAPELLA_NETWORKS under SpecFactoryTest

**Comment by StefanBratanov** [comment]
CI looks good. :) Can mark it ready for review and we will have a look and approve most likely.

**Review by rolfyone — APPROVED** [review]
LGTM

**Comment by StefanBratanov** [comment]
Hi @mxmar don't have access to rebase/merge master changes in your branch, but PR has been approved, so you can do one more merge/rebase and PR will be merged automatically.

**Pull request merged**
