### PR TITLE
Unhide DG detection option

### PR DESCRIPTION
**Pull request by mehdi-aouadi**
## PR Description
Unhide the doppelganger detection activation option

## Fixed Issue(s)

https://github.com/ConsenSys/teku/issues/6800

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM. the documented flags are development flags which is not optimal, I'm going to take a release candidate given the state of the docs, before this gets merge, and then it'll be consistent.

**Comment by rolfyone** [comment]
one thing that does concern me is this doesnt update any AT, which tends to suggest we have no AT for this feature...

**Comment by StefanBratanov** [comment]
> one thing that does concern me is this doesnt update any AT, which tends to suggest we have no AT for this feature...

It does update `TekuNode` and `TekuValidatorNode` which are used in AT.

**Comment by rolfyone** [comment]
> > one thing that does concern me is this doesnt update any AT, which tends to suggest we have no AT for this feature...
> 
> It does update `TekuNode` and `TekuValidatorNode` which are used in AT.

ah ok! That's fine then :)

**Pull request merged**
