### PR TITLE
8525 beacon states cleanup

### LINKED ISSUE #8525: clean up old BeaconStates.
We should probably provide at least a debug tool to cleanup the states table.

Currently if you switch from archive -> prune mode, we'll not load the archive tables so they're not accessible, but the data remains. Generally speaking, its likely that people are switching from archive mode to cleanup space, so it'd be nice to be able to at the very least clean this as a debug tool...

An alternative here would be to verify the table is empty when we start in prune or minimal mode and slowly clean it up if its not empty (oldest first), but this would be more complicated.... Maybe we should discuss the best option here...

### PR DESCRIPTION
**Pull request by mehdi-aouadi**
## PR Description
Clean up the finalized states after switching from ARCHIVE to MINIMAL or PRUNE mode.

## Fixed Issue(s)

fixes #8525 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM. It'll recover slowly this way but im not sure if we want to configure it to clean up more aggressively.... we'd easily be able to delete 1 state per minute for example, which would be x5 faster that this.

**Comment by mehdi-aouadi** [comment]
> LGTM. It'll recover slowly this way but im not sure if we want to configure it to clean up more aggressively.... we'd easily be able to delete 1 state per minute for example, which would be x5 faster that this.

We have the `--Xdata-storage-state-pruning-limit` and the `--Xdata-storage-state-pruning-interval` if we want to make it more agressive...

**Comment by rolfyone** [comment]
> We have the `--Xdata-storage-state-pruning-limit` and the `--Xdata-storage-state-pruning-interval` if we want to make it more agressive...

sure, but would you expect to need to set either of those options when you're just changing to minimal or prune mode ?

**Comment by mehdi-aouadi** [comment]
> > We have the `--Xdata-storage-state-pruning-limit` and the `--Xdata-storage-state-pruning-interval` if we want to make it more agressive...
> 
> sure, but would you expect to need to set either of those options when you're just changing to minimal or prune mode ?

Definitely not obvious. We can configure the pruner to delete 1 state per minute (if none of the `--Xdata-storage-state-pruning-limit` and `--Xdata-storage-state-pruning-interval` is set) when switching the storage mode as you suggested then, wdyt?
Here's a PR https://github.com/Consensys/teku/pull/8734

**Pull request merged**
