### PR TITLE
Replaced UInt64 with UnsignedLong

### LINKED ISSUE #108: UInt64 duplicates functionality in guava
https://github.com/PegaSysEng/artemis/blob/master/util/src/main/java/tech/pegasys/artemis/util/uint/UInt64.java

https://github.com/google/guava/blob/master/guava/src/com/google/common/primitives/UnsignedLong.java

### PR DESCRIPTION
**Pull request by craigwilliams84**
## PR Description
Replaced UInt64 with UnsignedLong from Guava

## Fixed Issue(s)
Fixes #108

### CODE REVIEW

**Comment by jrhea** [comment]
@craigwilliams84 thanks for doing this!!  It looks good to me at a glance.  I am going to assign the review to @schroedingerscode to look at though.

**Comment by schroedingerscode** [comment]
Thanks for the PR @craigwilliams84. I'll let @jrhea get all the 3 way merge conflicts sorted after his restructuring, then I'll take a look.

**Comment by jrhea** [comment]
@schroedingerscode should be good 2 go.  Thanks dude

**Review by schroedingerscode — APPROVED** [review]
This looks good to me. Thanks for your help!

**Pull request merged**
