### PR TITLE
Skip fork choice update if it has been processed

### LINKED ISSUE #7814: `/eth/v1/validator/attestation_data` taking a long time to respond
### Description

Teku takes significantly longer to respond to a request for attestation data made on `/eth/v1/validator/attestation_data` than other beacon nodes.

A recent example on mainnet showing the time taken to receive attestation data from four different beacon nodes:

screenshot_2023-12-11-234627

The calls to lighthouse, nimbus and prysm took a few milliseconds, whereas teku took 1-2 orders of magnitude longer.  Given that the attestation data should come directly from head state, this seems like a long time to have to wait for the data.

**Frequency:** [How regularly does it occur?]

Every slot.

### Versions (Add all that apply)

teku/v23.10.0/linux-x86_64/-privatebuild-openjdk64bitservervm-java-17

### PR DESCRIPTION
**Pull request by rolfyone**
Basically when preparing for attestations, we re-run FcU, and while we try to ensure this only happens once, we should be able to not run it at all now that FcU is run during block processing.

We should double check this on a testnet just to make sure the assertion that we can skip this extra FcU is correct. If it's an incorrect assertion we'd expect to see a significant decrease in finding the correct head in attestations.

fixes #7814

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
compared this against several nodes, looks good, will mark ready for review.

**Comment by tbenr** [comment]
have you measured any benefits? Asking because I suspect we are already skipping execution here:
https://github.com/ConsenSys/teku/blob/f31b239f7788f07d8e9c2b6e7544c5e16b01a259/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoiceRatchet.java#L63-L70

I'll do more checks

**Comment by rolfyone** [comment]
> have you measured any benefits? Asking because I suspect we are already skipping execution here: https://github.com/ConsenSys/teku/blob/f31b239f7788f07d8e9c2b6e7544c5e16b01a259/ethereum/statetransition/src/main/java/tech/pegasys/teku/statetransition/forkchoice/ForkChoiceRatchet.java#L63-L70
> 
> I'll do more checks

i could put a debug trace in, but im fairly sure its different... this way even via the ratchet we skip, so rather than being dependent on attestations running, it's just saying 'hey im already at current, im moving on'.

**Comment by rolfyone** [comment]
the allocation did appear in transfers, so i guess that's correct?
https://starkscan.co/contract/0x01aa168324d83d19ca99a529a34927f9d52ea65f8b726e555b3f42e32ddea658#token-transfers

**Comment by rolfyone** [comment]
@tbenr reminder

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
