### PR TITLE
Remove Kiln and Ropsten as supported networks

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Kiln and Ropsten have been shut down for a long time, so there is no point in supporting them as a `--network` option.

## Fixed Issue(s)
N/A

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by lucassaldanha — APPROVED** [review]

**Comment by lucassaldanha** [comment]
Might be worth adding a changelog entry? Not sure if you considered the fact that ppl using these configs (if any) won't be able to upgrade their nodes.

**Review by lucassaldanha — COMMENTED** [review]
Removing my approval for further discussion.

**Comment by rolfyone** [comment]
What's the logic behind removing ropsten?

ropsten.beaconcha.in shows blocks being produced..

**Comment by StefanBratanov** [comment]
> What's the logic behind removing ropsten?
> 
> ropsten.beaconcha.in shows blocks being produced..

Ropsten has been shut down since December last year though. **ropsten.beaconcha.in** points to mainnet for some reason and when you try connecting to it, there are no peers, etc.

**Comment by tbenr** [comment]
https://blog.ethereum.org/2022/11/30/ropsten-shutdown-announcement

**Comment by StefanBratanov** [comment]
Prysm also removed option few releases back: https://github.com/prysmaticlabs/prysm/pull/12058/

**Comment by lucassaldanha** [comment]
I got confused by ropsten.beaconcha.in

**Review by lucassaldanha — APPROVED** [review]

**Comment by rolfyone** [comment]
ok all good, just no context as to why we were removing support for a network still progressing, but happy now.

**Comment by StefanBratanov** [comment]
> I got confused by ropsten.beaconcha.in

Yeah same. I will bring it up in their discord.

**Review by tbenr — APPROVED** [review]

**Pull request merged**
