### PR TITLE
Allow spec presets to be override by config options

### LINKED ISSUE #4905: Cannot override SLOTS_PER_EPOCH in network config
### Description

I am trying to use web3signer with a custom network configuration to add web3signer support to our end to end testing suite in Prysm.
With this, I need to be able to override certain configuration for the remote signer. The web3signer supports the teku `--network` flag where a user can specify a yaml file to provide network configuration. The problem I have is that I am trying to provide a network configuration yaml file that extends and overrides some of the minimal network. 

Related issue: https://github.com/ConsenSys/web3signer/issues/494
Related PR: https://github.com/ConsenSys/web3signer/pull/496
Blocks: https://github.com/prysmaticlabs/prysm/pull/10123

### Steps to Reproduce (Bug)

```
./teku --network=/path/to/e2e_config.yaml
```

Here is the yaml in question.
```yaml
# e2e config

# Extends the minimal preset
PRESET_BASE: 'minimal'


# Transition
# ---------------------------------------------------------------
# TBD, 2**256-2**10 is a placeholder
TERMINAL_TOTAL_DIFFICULTY: 115792089237316195423570985008687907853269984665640564039457584007913129638912
# By default, don't use these params
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615



# Genesis
# ---------------------------------------------------------------
# [customized]
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 256 # Override for e2e tests
# Jan 3, 2020
MIN_GENESIS_TIME: 1578009600
# Highest byte set to 0x01 to avoid collisions with mainnet versioning
GENESIS_FORK_VERSION: 0x00000001
# [customized] Faster to spin up testnets, but does not give validator reasonable warning time for genesis
GENESIS_DELAY: 10 # Override for e2e tests


# Forking
# ---------------------------------------------------------------
# Values provided for illustrative purposes.
# Individual tests/testnets may set different values.

# Altair
ALTAIR_FORK_VERSION: 0x01000001
ALTAIR_FORK_EPOCH: 6 # Override for e2e
# Bellatrix
BELLATRIX_FORK_VERSION: 0x02000001
BELLATRIX_FORK_EPOCH: 18446744073709551615
# Sharding
SHARDING_FORK_VERSION: 0x03000001
SHARDING_FORK_EPOCH: 18446744073709551615


# Time parameters
# ---------------------------------------------------------------
# [customized] Faster for testing purposes
SECONDS_PER_SLOT: 10 # Override for e2e tests
# 14 (estimate from Eth1 mainnet)
SECONDS_PER_ETH1_BLOCK: 2 # Override for e2e tests
# 2**8 (= 256) epochs
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# [customized] higher frequency of committee turnover and faster time to acceptable voluntary exit
SHARD_COMMITTEE_PERIOD: 4 # Override for e2e tests
# [customized] process deposits more quickly, but insecure
ETH1_FOLLOW_DISTANCE: 4 # Override for e2e tests


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# [customized] scale queue churn at much lower validator counts for testing
CHURN_LIMIT_QUOTIENT: 65536


# Fork choice
# ---------------------------------------------------------------
# 70%
PROPOSER_SCORE_BOOST: 70


# Deposit contract
# ---------------------------------------------------------------
# Ethereum Goerli testnet
DEPOSIT_CHAIN_ID: 1337 # Override for e2e tests
DEPOSIT_NETWORK_ID: 1337 # Override for e2e tests
# Configured on a per testnet basis
DEPOSIT_CONTRACT_ADDRESS: 0x1234567890123456789012345678901234567890


# Other e2e overrides
# ---------------------------------------------------------------
CONFIG_NAME: "end-to-end"
SLOTS_PER_EPOCH: 6
EPOCHS_PER_ETH1_VOTING_PERIOD: 2
MAX_SEED_LOOKAHEAD: 1
```

**Expected behavior:** It loads the config provided and overrides the preset base.

**Actual behavior:** 
```
Unable to load configuration for network "/path/to/e2e_config.yaml": Found duplicate declarations for spec constant 'SLOTS_PER_EPOCH' with divergent values: '6' and '8'
```

**Frequency:** Every time.

### Versions (Add all that apply)
* Software version: `teku/v22.1.0+52-g6648486/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11`
* Java version:
```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
* OS Name & Version: 

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

* Docker Version: None
* Cloud VM, type, size: N/A

### PR DESCRIPTION
**Pull request by prestonvanloon**
## PR Description

I would like to use web3signer with a config that overrides some spec presets such that web3signer can use Prysm's end to end minimal preset files with overrides. This is very valuable to the Prysm project as we could introduce web3signer to our automated end to end testing.

Rather than returning an IllegalArgumentException, I have logged a warning message to users as this behavior is typically non-standard.

## Fixed Issue(s)

Fixes #4905

## Documentation

- [ ] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Hold up: test fails so I need to think about it a bit more as a draft.

**Comment by ajsutton** [comment]
The spotless failure can be fixed by running `./gradlew spotlesssApply` for the record.

**Comment by ajsutton** [comment]
And the windows build is failing because of spotless too (it runs the same build process but on windows so will fail if most of the other steps fail)

**Comment by prestonvanloon** [comment]
> [CLA assistant check](https://cla-assistant.io/ConsenSys/teku?pullRequest=4921) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ConsenSys/teku?pullRequest=4921) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ConsenSys/teku?pullRequest=4921) it.

CLA assistant is not working

Screenshot from 2022-01-31 20-58-02

**Comment by ajsutton** [comment]
> CLA assistant is not working

hmm, that's a new one.  It is working now for me though it does take a 5 seconds or so to load the actual agreement.

**Review by rolfyone — APPROVED** [review]
LGTM

**Comment by ajsutton** [comment]
Thanks for getting this started @prestonvanloon

**Pull request merged**
