### PR TITLE
Introduce metrics abstraction

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Introduces the abstraction layer for metrics capture from Pantheon.

A `MetricsSystem` instance is created and added to the `ServiceConfig` object so each service can create counters/gauges/etc as needed which are then reported through the Prometheus endpoint provided by the `MetricsServer` service.

Note that in a micro service future, each micro service would run its own `MetricsServer` service and have an independent `MetricsSystem` instance but we only want a single prometheus endpoint per JVM instance.

I'm not 100% sure `MetricsService` should be an actual service but it needs to tie into life-cycle so it seems to fit.

## Related Issue(s)
#712

### CODE REVIEW

**Review by jrhea — CHANGES_REQUESTED** [review]
Looking good so far.  Instead of making it a service, I would just let it live in the BeaconNode.  Service can send data to the MetricsSystem via the eventbus. 

Instead of modifying the ServiceController, I would just instantiate and run it in the BeaconNode.  There is an event that fires from StateProcessor every slot that you can catch and use to push data.  It used to be handled in BeaconNode directly, but it doesn't seem to be anymore.  Here is a link to the method that triggers the event:
https://github.com/PegaSysEng/artemis/blob/2c021e887743bd393685d2b801043576f7eefb6d/ethereum/statetransition/src/main/java/tech/pegasys/artemis/statetransition/StateProcessor.java#L294

For now, just see if you can handle the RawRecord event directly and go from there.

All that being said, you might have compelling rationale to make it into a service.....if that is the case, then i can walk you through the pattern.

**Comment by ajsutton** [comment]
Yeah I think making the metrics endpoint a service was a mistake - I've changed the actual endpoint to stay in `BeaconNode`.  Currently the `MetricsSystem` is still being provided via `ServiceConfig`.

I think there are two possible approaches to using metrics which would factor into how we do this.

If we only wanted to expose the metrics from the standard, then yes keeping it isolated to just `BeaconNode` and capturing events via the event bus makes sense. `MetricsSystem` then wouldn't be in `ServiceConfig` and services would know absolutely nothing about metrics.

But I'm inclined to add metrics to capture quite a lot of information about what Artemis is doing so it can be monitored effectively. That's been extremely powerful in Pantheon. One good example of those metrics would be a counter of total events received on the event bus.  If we did later deploy services as separate micro-services and the event bus became network driven, you'd want to have alerts go off if the event counter didn't increment for some period of time as that would indicate a network split has occurred.  Even now we might want counters to record the number of network messages received (potentially labelled with the type of message).

For that level of metrics, publishing an event every time a metric changes is too much overhead and can easily swamp the event bus (and leads to an infinite loop for our event counter...).  It may still make sense to capture some metrics off of events but many metrics will be exposing some internal state that is useful to monitor like queue sizes so are better done in-place.

**Comment by jrhea** [comment]
@ajsutton i dig your second plan.

**Review by jrhea — APPROVED** [review]
lgtm

**Pull request merged**
