### PR TITLE
Re-run failed tests CircleCI functionality

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Implementing for `integrationTests` and `acceptanceTests`, since other tests are not flaky.

https://circleci.com/docs/rerun-failed-tests-only/

## Fixed Issue(s)
will fix an internal issue

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
**integrationTests** failing with 

```
#!/bin/bash -eo pipefail
circleci tests run --command="./gradlew --no-daemon --parallel integrationTest"

Installing circleci-tests-plugin-cli plugin.
circleci-tests-plugin-cli plugin Installed. Version: 1.0.6601-306bc14
WARN[2023-07-03T10:08:35Z] No test names found in input source. If you were expecting test names, please check your input source. 
CircleCI received exit code 0
```

**Comment by StefanBratanov** [comment]
`acceptanceTests` fail as well: https://app.circleci.com/pipelines/github/Consensys/teku/26296/workflows/6f4b8305-e60e-4f99-9257-5fb7e02887ec/jobs/192489

**Comment by lucassaldanha** [comment]
@StefanBratanov can we close this ticket?

**Comment by StefanBratanov** [comment]
Yes, let's close this PR. Not needed as of now and wasn't super straight forward to do.

**Pull request closed without merging**
