### PR TITLE
Unhide builder bid compare factor and fix win logging

### PR DESCRIPTION
**Pull request by zilm13**
## PR Description
This PR is based on #6971, which should be merged before this one
- Option is unhided, plus name was changed and code all the way updated to refer to the new name
- Changelog entry added

Documentation PR will be made after this one merged

UPDATE: as #6971 is closed with all changes applied here, copying its contents, it's fixed here too:
- Fix local execution payload value challenge won log. Currently logs local value on a place of bid value and vice versa. Plus readability improved
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
moving it here. Likely needs to be updated

```
### builder-bid-compare-factor

<!--tabs-->

# Syntax

``bash
--builder-bid-compare-factor=<INTEGER>
``

# Example

``bash
--builder-bid-compare-factor=50
``

# Environment variable

``bash
TEKU_BUILDER_BID_COMPARE_FACTOR=50
``

# Configuration file

``bash
builder-bid-compare-factor: 50
``

<!--/tabs-->

Changes validator's builder bid compare factor. The default value is 100 (100%).

Since Capella fork local execution payload contains its value, the validator client could use it over builder bid when it's higher or equal. Operator could override the factor, in this case 50 means builder bid is considered at 50% value, so it should be at least twice bigger to win over local payload and used for block production, contra 200 would mean use builder bid over local payload even if it's smaller up to 2 times.
```

**Comment by zilm13** [comment]
Was working on this. Check it

```

### builder-bid-compare-factor

<!--tabs-->

# Syntax

``bash
--builder-bid-compare-factor=<STRING>
``

# Example

``bash
--builder-bid-compare-factor=50
``

# Environment variable

``bash
TEKU_BUILDER_BID_COMPARE_FACTOR=50
``

# Configuration file

``bash
builder-bid-compare-factor: 50
``

<!--/tabs-->

Changes validator's builder bid compare factor. The default value is 100 (100%).

Starting from Shapella fork local execution payload contains its value, so beacon node could compare it against the builder bid in order to maximize validators profit or improve network censorship at low or no cost. 

Set the compare factor applied to the builder bid value when comparing it with locally produced payload. Factor is expressed in percentage (e.g. `100` means locally produced payload will be chosen when its value is equal or greater than the entire builder bid value, `80` means local payload will be chosen when its value is at least 80% of builder bid value).

Set it to `BUILDER_ALWAYS` to always use builder bid. Locally produced payload will be used only when the bid is invalid.
```

**Review by tbenr — APPROVED** [review]
LGTM

**Comment by benjaminion** [comment]
> Starting from Shapella fork

Ugh - can we never ever say "Shapella", please 🤮

"Shanghai–Capella" (yes, that's an [en dash](https://www.grammarly.com/blog/en-dash/) between them).

**Pull request merged**
