### PR TITLE
Unhide IPv6/dual-stack options

### LINKED ISSUE #8069: Enhanced IPv6 support
### Description
Currently Teku will serve on ipv6 only when ipv4 is not enabled. But there is a common usage case to run both IPv4 and IPv6. Also we miss any configuration for it: setting different ports, advertising ipv6 etc. Check, for example, lighthouse configuration:
https://lighthouse-book.sigmaprime.io/advanced_networking.html#ipv6-support

#### Remaining Tasks:
- [x] return Optional<List<String>> in `DiscV5Service.getDiscoveryAddress`
- [x] When we are searching for peers and streaming known peers, we only use `nodeRecord.getTcpAddress()` to connect to them. We should also see how we can use `nodeRecord.getTcp6Address`.
- [x] Port forward the upd IPv6 port

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Unhide IPv6/dual-stack CLI options

## Fixed Issue(s)
fixes #8069 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — DISMISSED** [review]
one note, this does kind of indicate there's no tests around any of these flags that were dev flags, as not one test broke... Maybe we should at least have a test that sets all the flags and checks values, and also maybe one that checks defaults?

**Comment by StefanBratanov** [comment]
> one note, this does kind of indicate there's no tests around any of these flags that were dev flags, as not one test broke... Maybe we should at least have a test that sets all the flags and checks values, and also maybe one that checks defaults?

Good point. I will add couple of tests.

**Comment by StefanBratanov** [comment]
Dual-stack testing on Azure VMs

```json
{
  "data": {
    "peer_id": "16Uiu2HAmS2wbEc4uWrG4wgt9Q9M6CqpbkrjjZVLQNqZ166dqG4Eq",
    "enr": "enr:-Ne4QF5D0VupPdhSKWZ3f2BlS6hiyu6Gcz1n588EcIFhXJbuPGJaj5KxsG7YNCElJWL8Y0Ir38-GKJnRt-c5jst79HISh2F0dG5ldHOIYAAAAAAAAACEZXRoMpBprg6ZBQFwAP__________gmlkgnY0gmlwhDSTE9aDaXA2kCYDEBAAAgACAAAAAAAAAMiJc2VjcDI1NmsxoQPGx5ZsyWMK75P7njAVf5DetfkkfyPA4USwmJI0nn18JoN0Y3CCIyiEdGNwNoIjgoN1ZHCCIyiEdWRwNoIjgg",
    "p2p_addresses": [
      "/ip4/52.147.19.214/tcp/9000/p2p/16Uiu2HAmS2wbEc4uWrG4wgt9Q9M6CqpbkrjjZVLQNqZ166dqG4Eq",
      "/ip6/2603:1010:2:2::c8/tcp/9090/p2p/16Uiu2HAmS2wbEc4uWrG4wgt9Q9M6CqpbkrjjZVLQNqZ166dqG4Eq"
    ],
    "discovery_addresses": [
      "/ip4/52.147.19.214/udp/9000/p2p/16Uiu2HAmS2wbEc4uWrG4wgt9Q9M6CqpbkrjjZVLQNqZ166dqG4Eq",
      "/ip6/2603:1010:2:2::c8/udp/9090/p2p/16Uiu2HAmS2wbEc4uWrG4wgt9Q9M6CqpbkrjjZVLQNqZ166dqG4Eq"
    ],
    "metadata": {
      "seq_number": "1",
      "attnets": "0x6000000000000000",
      "syncnets": "0x00"
    }
  }
}
```

Getting inbound/outbound connections

```json
{
  "direction": "inbound",
  "count": 19
}
{
  "direction": "outbound",
  "count": 51
}
```

**Comment by StefanBratanov** [comment]
Tested locally with two nodes (IPv6 only)

image

**Comment by StefanBratanov** [comment]
Tested on Azure VMs:

First VM with second VM as a static peer (outbound):
image

Second VM has first VM as a peer (inbound)
image

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
