### PR TITLE
Improve the two "key" serializers in kvstore

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

I was reviewing these and thought they could be a little cleaner/safer.

* Add constants for each field's size and offset.
* Add `checkArgument` to ensure the input is the right length.
* Add `UInt64Serializer::deserialize` helper function.
* Add property tests to ensure they work as intended.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
Hey @jtraglia thanks! Makes sense, especially the length checks, but I'd also like to avoid too many boxing\wrapping. I'll take a closer look over the weekend or Monday.

**Comment by jtraglia** [comment]
Okay sounds good. There's no rush. Feel free to push changes to this PR.

**Comment by tbenr** [comment]
@jtraglia you won't probably like that much :) but seems safe enough for me since sizes are checked at the beginning.

**Comment by jtraglia** [comment]
I think I'm okay with this! I like that the deserialization function is in `UInt64Serializer` now. That's a better place for it.

**Review by tbenr — APPROVED** [review]
LGTM

**Comment by jtraglia** [comment]
I'd like to add some more info to the javadoc for that new function before merging. I can do this.

**Comment by tbenr** [comment]
@jtraglia feel free to do so

**Comment by jtraglia** [comment]
Thanks. Done. Just felt a little empty.

**Pull request merged**
