### PR TITLE
Use 16-bit random value in validator filter

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

This PR implements the changes defined here:

* https://github.com/ethereum/consensus-specs/pull/4039

Notably, this PR will:

* Override `computeProposerIndex` and `getNextSyncCommitteeIndices`.
* In `computeProposerIndex`, rename `hash` to `randomBytes` to match the spec.
* Add cached `randomBytes` to `getNextSyncCommitteeIndices`.
* Define new `MAX_RANDOM_VALUE` equal to `2**16-1`.

See the original implementations here:

https://github.com/Consensys/teku/blob/7de9aa456a0bf96c773beb541b113a60c2b56a6b/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/common/helpers/MiscHelpers.java#L112-L139

https://github.com/Consensys/teku/blob/7de9aa456a0bf96c773beb541b113a60c2b56a6b/ethereum/spec/src/main/java/tech/pegasys/teku/spec/logic/versions/altair/helpers/BeaconStateAccessorsAltair.java#L104-L132

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
in this PR we should re-enable2 fizzing tests disabled here: https://github.com/Consensys/teku/pull/8923

**Comment by jtraglia** [comment]
Hmm I'm not sure why these are still failing. The only difference is the `body_root`.

image

**Comment by rolfyone** [comment]
> Hmm I'm not sure why these are still failing. The only difference is the `body_root`.

I've got a body root diff in mine too...

**Comment by tbenr** [comment]
this is weird. I'll spend some more time on it tomorrow, if in the meantime you don't solve the mystery

**Comment by tbenr** [comment]
lol, my bad. Seems like I copied the wrong spec files. I also fixed a uint test that seems to be affected by the change

**Comment by jtraglia** [comment]
Haha no worries. Thank you for fixing this. Comparing `prettySerialize` outputs is a good idea too!

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
