### PR TITLE
move to reference tests 1.1.0

### PR DESCRIPTION
**Pull request by tbenr**
ignored common tests:
* merkle/single_proof

ignored merge tests:
* fork_choice/on_merge_block
* genesis/initialization
* genesis/validity

updates `TERMINAL_TOTAL_DIFFICULTY` as per latest spec

## Documentation

- [X] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
@regio this time happened in CI: the UT `shouldRunPublisherEveryXSeconds()`

**Comment by Nashatyrev** [comment]
> @regio this time happened in CI: the UT `shouldRunPublisherEveryXSeconds()`

Restarted CI job. Does it make sense to create an issue on this flaky test?

**Review by Nashatyrev — APPROVED** [review]
LGTM

**Comment by ajsutton** [comment]
> > @regio this time happened in CI: the UT `shouldRunPublisherEveryXSeconds()`
> 
> Restarted CI job. Does it make sense to create an issue on this flaky test?

Yes please. That's quite a new test - @regio I think it's part of the new metrics publishing tests so probably worth looking at.

**Pull request merged**
