### PR TITLE
Fixed the request body of validator liveness endpoint

### LINKED ISSUE #7204: `liveness` endpoint not conform to the specification?
The Beacon API `v2.4.0` defines the [getLiveness endpoint](https://ethereum.github.io/beacon-APIs/#/Validator/getLiveness) as following:

- **Verb:** POST
- **Endpoint:**  `/eth/v1/validator/liveness/{epoch}`
- **Body example:** 
```
["1", "42", "1664"]
```
(List of indexes)

However, the Teku implements the [getLiveness endpoint](https://docs.teku.consensys.net/api#tag/Experimental/operation/postValidatorLiveness) in a slightly different way:
- **Verb:** POST (same)
- **Endpoint:**  `/eth/v1/validator/liveness/{epoch}` (same)
- **Body example:** 
```
{
   "indices": [
      "1",
      "42",
      "1663"
   ]
}
```
(Map with `indices` as key and with a list of indexes as value)

Is there any specific reason not to conform to the specification?
If no, would it be possible to adapt it?
If you don't want do break retro-compatibility, I guess it's possible for the endpoint to accept both current Teku body and ETH beacon API specification body.

### PR DESCRIPTION
**Pull request by rolfyone**
Also removed the `experimental` tag as it's used in doppelganger feature.

fixes #7204

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by StefanBratanov — CHANGES_REQUESTED** [review]
I think we need to also change `OkHttpValidatorRestApiClient` in this PR to conform to the spec, since `ValidatorLivenessRequest` is still using the other input. Otherwise VC and BN compatibility would break.

**Review by mehdi-aouadi — DISMISSED** [review]
We could also remove `ValidatorLivenessRequest` since it's not used anymore

**Comment by rolfyone** [comment]
> We could also remove `ValidatorLivenessRequest` since it's not used anymore

ppl - comments are fine, not sure i'm a huge fan of spamming 'changes requested'

**Comment by rolfyone** [comment]
> I think we need to also change `OkHttpValidatorRestApiClient` in this PR to conform to the spec, since `ValidatorLivenessRequest` is still using the other input. Otherwise VC and BN compatibility would break.

this was done at the bottom of the changes list, are there more changes you were expecting? because the change currently there is what you're talking about as far as I can see...

**Review by StefanBratanov — APPROVED** [review]
Oh yes, sorry. I somehow missed on these changed files.

**Comment by rolfyone** [comment]
@mehdi-aouadi you've taken ownership to merge this with your changes-requested flag.

**Pull request merged**
