### PR TITLE
Some optimizations for epoch transition

### PR DESCRIPTION
**Pull request by tbenr**
avoid some Bytes wrapping, especially during epoch transition, when `shuffleList` is called, which currently calls `intToBytes` 25 million times!

use thread local `sha256` where still not used.

old:
image

new:
image

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM, you've shown memory used, is it actually taking less time to process also?

**Comment by tbenr** [comment]
A bit less, but hashing here is the big cpu consumption

**Comment by tbenr** [comment]
A bit less, but hashing here is the big cpu.

I'll check it again cose it should be better to have a local sha256 here to avoid millions of lookups to thread local

**Comment by tbenr** [comment]
actually there isn't much difference in cpu even switching back to local sha256.
but the overall `shuffleList` memory allocation is nicely reduced:

new
image

old
image

**Pull request merged**
