### PR TITLE
[MERGE] Support overriding total terminal difficulty

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Adds a `--Xnetwork-merge-total-terminal-difficulty` option to override the terminal total difficulty for the merge.

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM

**Comment by Nashatyrev** [comment]
@ajsutton thanks for this PR it would be really handy for interop!
There is an idea to set the TTD in Execution Layer client and then fetch it on startup via EL API. But that's just an idea for now

**Comment by Nashatyrev** [comment]
Found out the strange thing; while that was successfully built on CI, on our local machines (mine and @tbenr ) the `UInt256` dependency is missing in `ethereum.networks` project. 

The below patch fixes the problem: the `UInt256` is transitively available via the `spec` project when the `tuweny-units` is imported via `api`. Just curious why this PR passed the build. (BTW the merge commit has failed)

```patch
Index: ethereum/spec/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- ethereum/spec/build.gradle	(revision 55fd5783310db80fb49cadf2e9b4dba0f9500138)
+++ ethereum/spec/build.gradle	(date 1633418454088)
@@ -42,7 +42,7 @@
     implementation 'com.google.code.gson:gson'
     implementation 'org.apache.tuweni:tuweni-bytes'
     implementation 'org.apache.tuweni:tuweni-crypto'
-    implementation 'org.apache.tuweni:tuweni-units'
+    api 'org.apache.tuweni:tuweni-units'
     implementation 'org.apache.tuweni:tuweni-ssz'
 
     testImplementation testFixtures(project(':bls'))
```

**Comment by Nashatyrev** [comment]
Well found the answer: 
Before merging with `master` the `tuweni-units` was transitively picked up via `spec -> util -> metrics`. `util -> metrics` dependency was removed with master merge PR

**Comment by ajsutton** [comment]
Yep, you found it before I could hit enter. :) 

I made dependencies more explicit on master today so there may have been some interaction around that I guess. Not sure that we're enforcing that PRs be up to date with the latest merge-interop commits which maybe makes the difference here...

**Pull request merged**
