### PR TITLE
Schedule Deneb for Gnosis

### LINKED ISSUE #7975: Schedule Gnosis dencun hardfork
Deneb scheduled for:

```
Slot: 14237696
Epoch: 889856
Timestamp: 1710181820
Date: UTC Mon 11/03/2024, 18:30:20
```

- Config PR https://github.com/gnosischain/configs/pull/33
- Announcement: https://www.gnosis.io/blog/gnosis-chain-cancun-deneb-dencun-hard-fork-announcement

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description

- Schedule Gnosis for Deneb upgrade for epoch 889856

## Fixed Issue(s)
fixes #7975 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by zilm13 — COMMENTED** [review]
I'd add also 
```
.trustedSetupFromClasspath(MAINNET_TRUSTED_SETUP_FILENAME)
```
in `Eth2NetworkConfiguration`

Also I see some differences with https://raw.githubusercontent.com/gnosischain/specs/master/consensus/config/gnosis.yaml at least `MIN_EPOCHS_FOR_BLOCK_REQUESTS`

**Comment by StefanBratanov** [comment]
> I'd add also
> 
> ```
> .trustedSetupFromClasspath(MAINNET_TRUSTED_SETUP_FILENAME)
> ```
> 
> in `Eth2NetworkConfiguration`
> 
> Also I see some differences with https://raw.githubusercontent.com/gnosischain/specs/master/consensus/config/gnosis.yaml at least `MIN_EPOCHS_FOR_BLOCK_REQUESTS`

Very good catches. Thanks. Done!

**Review by zilm13 — APPROVED** [review]
LGTM

**Comment by dapplion** [comment]
Thank you so much for the quick inclusion! Will this PR be included in the Ethereum mainnet dencun release?

**Comment by StefanBratanov** [comment]
> Thank you so much for the quick inclusion! Will this PR be included in the Ethereum mainnet dencun release?

No worries! Yup. The release is cooking now. 👨‍🍳

**Pull request merged**
