### PR TITLE
Remove unused methods on ExecutionPayloadBuilder

### PR DESCRIPTION
**Pull request by lucassaldanha**
## PR Description
- Remove old methods in `ExecutionPayloadBuilder` that are not being used anymore.

## Fixed Issue(s)
N/A

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by rolfyone — APPROVED** [review]
LGTM

**Review by gfukushima — APPROVED** [review]
lgtm, do we need to include executionRequests on the builder later on?

**Comment by gfukushima** [comment]
missed removing some references in the EL Stub

**Comment by lucassaldanha** [comment]
> missed removing some references in the EL Stub

Remaining EL stub references are removed in this other PR: https://github.com/Consensys/teku/pull/8717

**Comment by lucassaldanha** [comment]
> lgtm, do we need to include executionRequests on the builder later on?

They are in another PR: https://github.com/Consensys/teku/pull/8717

**Pull request merged**
