### PR TITLE
[MEV Boost\Builder] Implement builder_status and health check

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
**Tasks:**

Retrieve builder status and implement `isBuilderAvailable`
Track builder flow availability

**Changes:**
- Introduced `ExecutionLayerManager`
- Added `isBuilderAvailable` implementation to `ExecutionLayerManager`
- Added `onSlot` logic to `ExecutionLayerManager` to track and update the builder flow availability

## Fixed Issue(s)
related to #5396 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by tbenr — APPROVED** [review]
LGTM but I'm still rethinking about this: having the healthcheck in the `ExecutionLayerService` makes `ExecutionLayerChannelImpl` unaware of the current status (which makes sense to be aware in case we want to immediately skip to calls based on that)

**Comment by StefanBratanov** [comment]
> LGTM but I'm still rethinking about this: having the healthcheck in the `ExecutionLayerService` makes `ExecutionLayerChannelImpl` unaware of the current status (which makes sense to be aware in case we want to immediately skip to calls based on that)

Let me try implementing it in the Impl and see the difference. It should be a quick one.

**Comment by tbenr** [comment]
But it could be just a peek in the impl.. let's have a quick chat tomorrow if you don't find a quick nice solution

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
