### PR TITLE
Remove jupnp workaround

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
Removes an old TODO
It was fixed as part of Release JUPnp 2.6.0: https://github.com/jupnp/jupnp/releases/tag/2.6.0

## Fixed Issue(s)
N/A

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
looks very reasonable. If we trust our own comments we could go for it. I'd like to do an actual test on my router. I'll try to do it tomorrow.

**Review by rolfyone — APPROVED** [review]
LGTM

**Review by lucassaldanha — APPROVED** [review]
LGTM

**Comment by StefanBratanov** [comment]
Just want to wait for @tbenr 's testing the change on his router and will merge.

**Comment by tbenr** [comment]
```
2023-03-06 18:14:40.016 INFO  - Starting UPnP Service
2023-03-06 18:14:40.017 INFO  - Syncing     *** Target slot: 5941571, Head slot: 0, Remaining slots: 5941571, Connected peers: 0
2023-03-06 18:14:40.033 FATAL - Teku failed to start
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: javax/servlet/Servlet
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1159) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[classes/:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:887) ~[?:?]
at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2325) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:626) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$34(SafeFuture.java:426) ~[classes/:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:148) ~[classes/:?]
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863) ~[?:?]
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841) ~[?:?]
at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateToAsync$20(SafeFuture.java:326) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:82) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:47) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:124) ~[classes/:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: javax/servlet/Servlet
at org.jupnp.transport.impl.jetty.JettyTransportConfiguration.createStreamServer(JettyTransportConfiguration.java:37) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.DefaultUpnpServiceConfiguration.createStreamServer(DefaultUpnpServiceConfiguration.java:184) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:416) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:125) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:258) ~[org.jupnp-2.6.1.jar:?]
at tech.pegasys.teku.networking.nat.UpnpClient.startup(UpnpClient.java:63) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatManager.doStart(NatManager.java:53) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatService.doStart(NatService.java:54) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[classes/:?]
at tech.pegasys.teku.services.ServiceController.lambda$doStart$0(ServiceController.java:33) ~[classes/:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
... 27 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
at org.jupnp.transport.impl.jetty.JettyTransportConfiguration.createStreamServer(JettyTransportConfiguration.java:37) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.DefaultUpnpServiceConfiguration.createStreamServer(DefaultUpnpServiceConfiguration.java:184) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:416) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.transport.RouterImpl.enable(RouterImpl.java:125) ~[org.jupnp-2.6.1.jar:?]
at org.jupnp.UpnpServiceImpl.startup(UpnpServiceImpl.java:258) ~[org.jupnp-2.6.1.jar:?]
at tech.pegasys.teku.networking.nat.UpnpClient.startup(UpnpClient.java:63) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatManager.doStart(NatManager.java:53) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatService.doStart(NatService.java:54) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:35) ~[classes/:?]
at tech.pegasys.teku.services.ServiceController.lambda$doStart$0(ServiceController.java:33) ~[classes/:?]
at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
... 27 more
```

--p2p-nat-method=UPNP

@StefanBratanov does run for you?
It doesn't happen without this PR

**Comment by tbenr** [comment]
btw `2.7.0` came out 2 days ago

**Comment by StefanBratanov** [comment]
Thanks @tbenr , actually didn't run Teku with that parameter. I also got the error. It's related to the Jetty implementation of the StreamClient. I revived the TekuNatServiceConfiguration, but just implemented two of the methods to use OkHttpClient.

**Comment by tbenr** [comment]
I see. Run again and it worked.
I noticed that I get 
```
2023-03-06 19:11:56.252 WARN  - Failed to startup UPnP service
java.util.concurrent.CancellationException: null
at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478) ~[?:?]
at tech.pegasys.teku.networking.nat.UpnpClient.shutdown(UpnpClient.java:69) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatManager.lambda$doStop$2(NatManager.java:66) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$alwaysRun$28(SafeFuture.java:356) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$thenPeek$37(SafeFuture.java:493) ~[classes/:?]
at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApply(SafeFuture.java:467) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.thenPeek(SafeFuture.java:491) ~[classes/:?]
at tech.pegasys.teku.infrastructure.async.SafeFuture.alwaysRun(SafeFuture.java:356) ~[classes/:?]
at tech.pegasys.teku.networking.nat.NatManager.doStop(NatManager.java:66) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.stop(Service.java:42) ~[classes/:?]
at java.util.Optional.map(Optional.java:260) ~[?:?]
at tech.pegasys.teku.networking.nat.NatService.doStop(NatService.java:67) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.stop(Service.java:42) ~[classes/:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
at tech.pegasys.teku.services.ServiceController.doStop(ServiceController.java:40) ~[classes/:?]
at tech.pegasys.teku.service.serviceutils.Service.stop(Service.java:42) ~[classes/:?]
at tech.pegasys.teku.AbstractNode.stop(AbstractNode.java:199) ~[classes/:?]
at tech.pegasys.teku.Teku.lambda$main$0(Teku.java:50) ~[classes/:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```

during shutdown when no UPnp router is found.

**Comment by StefanBratanov** [comment]
@tbenr do you get this error without this PR, I can't reproduce on my machine.

**Comment by tbenr** [comment]
@StefanBratanov ah yes I ended up reproducing it with current master too.. so LGTM

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
