### PR TITLE
Add Codespell workflow

### PR DESCRIPTION
**Pull request by miles-six**
## PR Description

I fix many typos and want to add workflow for codespell check to eliminate all typos in the future.

I have added a relatively simple filtering file to exclude certain words. 

If you find it meaningful, you can modify the filtering conditions according to your needs.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
Hi @miles-six , thanks for raising a PR. I like the idea of having some spell check running, but I see from the failed action on the PR that a lot of the errors are in the java code when importing (e.g. `errorprone`) or annotations `@AfterAll`. Is there a way to make `codespell` more Java aware?

**Comment by miles-six** [comment]
> Hi @miles-six , thanks for raising a PR. I like the idea of having some spell check running, but I see from the failed action on the PR that a lot of the errors are in the java code when importing (e.g. `errorprone`) or annotations `@AfterAll`. Is there a way to make `codespell` more Java aware?

We can add these words to words.txt to skip check

**Comment by miles-six** [comment]
@StefanBratanov  The case is not distinguished, and the default is lowercase. If you want to skip check of 'Word' , it should be written as 'word' in the wordlist.txt file. And now it's completed

**Comment by StefanBratanov** [comment]
Looks good, I think though these 3 words are legit typos and require fixing:

- vie -> via
- uptodate -> up-to-date
- whats -> what's

**Comment by miles-six** [comment]
> Looks good, I think though these 3 words are legit typos and require fixing:
> 
> * vie -> via
> * uptodate -> up-to-date
> * whats -> what's

yes,I updated the word.txt and fixed them!

**Comment by StefanBratanov** [comment]
Thanks for the PR. :) Happy to merge this. Can you just please rename the PR to `Add Codespell workflow` to be more descriptive and we will merge it.

**Comment by miles-six** [comment]
> Thanks for the PR. :) Happy to merge this. Can you just please rename the PR to `Add Codespell workflow` to be more descriptive and we will merge it.

@StefanBratanov  Thanks for your response, I have renamed it!

**Review by StefanBratanov — APPROVED** [review]
LGTM

**Pull request merged**
