### PR TITLE
Add max epoch activation churn limit for Deneb

### LINKED ISSUE #7520: Add max epoch activation churn limit (EIP-7514)
https://github.com/ethereum/consensus-specs/pull/3499

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description
- Introduced `getValidatorActivationChurnLimit` in `BeaconStateAccessors` and overrode it in `BeaconStateAccessorsDeneb`
- Added `MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT` to `SpecConfigDeneb` to all config files, which have deneb config params already.
- Enabled `--Xfork-choice-proposer-boost-uniqueness-enabled` to true by default
- Bumped up ref test version to `v1.4.0-beta.2-hotfix`
- Disabled running the new Deneb fork-choice tests. Raised https://github.com/Consensys/teku/issues/7539 to support those tests.
- Changed one of the post.ssz in FuzzUtilTest because the post state has changed with the new release - https://github.com/ethereum/consensus-spec-tests/tree/master/tests/minimal/capella/operations/attester_slashing/pyspec_tests/basic_surround

## Fixed Issue(s)
fixes #7520 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
Waiting for v1.4.0-beta.2 release of consensus-spec-tests

**Comment by StefanBratanov** [comment]
> Waiting for v1.4.0-beta.2 release of consensus-spec-tests

PR updated with latest version

**Review by tbenr — COMMENTED** [review]
LGTM. I just want to double-check if there is any config param breaking change.
Like `maxPerEpochActivationChurnLimit` becomes mandatory and a VC with this PR doesn't start against a BN without this PR

**Comment by StefanBratanov** [comment]
> LGTM. I just want to double-check if there is any config param breaking change. Like `maxPerEpochActivationChurnLimit` becomes mandatory and a VC with this PR doesn't start against a BN without this PR

Good point. Thanks for checking. Shouldn't break until both are on Deneb in which case, both VC and BN should have been updated anyways.

**Review by tbenr — APPROVED** [review]
LGTM

**Pull request merged**
