### PR TITLE
Latest Grafana requires root insider contaioner to run correctly

### PR DESCRIPTION
**Pull request by Neurone**
## Fixed Issue(s)
Starting the test-network with `launch.sh` Grafana stops with the following error:

```txt
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
```

The problem is due to changes in the permissions inside the container and in particular to the modifications done in [new Grafana docker images](https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v73-or-later).

To fix this you can intervene with post start modifications, or you can create grafana folders with `user` permissions (modified `launch.sh`) and set the group as `root`. I applied the latter.

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by ajsutton — APPROVED** [review]
LGTM. Thanks for this.  I'd forgotten we had grafana running in that test setup actually.

**Comment by ajsutton** [comment]
I don't have permission to push to this branch, could you update it to the latest head please so I can merge it?

**Comment by Neurone** [comment]
> I don't have permission to push to this branch, could you update it to the latest head please so I can merge it?

Sure, done.

**Comment by benjaminion** [comment]
I did the merge. Thanks for fixing this!

**Pull request merged**
