### PR TITLE
Update gradle version to 6.4.1

### PR DESCRIPTION
**Pull request by usmansaleem**
-- Update gradle version to 6.4.1
-- Allows builds with JDK 14

Signed-off-by: Usman Saleem <usman@usmans.info>

### CODE REVIEW

**Comment by ajsutton** [comment]
This should fix https://github.com/PegaSysEng/teku/issues/1788 when it's done.  Interestingly @benjaminion reported a build failure on one of his machines when doing this update.  Seems to work from a clean build though so it's possible that a `./gradlew clean` is required in some cases.

**Comment by usmansaleem** [comment]
@ajsutton The trick was to use JDK 13 to run gradle wrapper. Even gradle wrapper was failing for JDK 14.

**Comment by ajsutton** [comment]
I assume you mean just for the first download?  And that shouldn't be a problem now we have the updated wrapper jar?

**Review by ajsutton — APPROVED** [review]
LGTM.

**Comment by usmansaleem** [comment]
> I assume you mean just for the first download? And that shouldn't be a problem now we have the updated wrapper jar?

Yes, correct :).

**Pull request merged**
