### PR TITLE
Add query parameters to readiness API for required proposer information/registrations

### PR DESCRIPTION
**Pull request by StefanBratanov**
## PR Description

- Add two query parameters to the admin `/readiness` endpoint: `require_prepared_proposers` and `require_validator_registrations` which are by default false.
- Added `nodeDataProvider` in `AbstractMigratedBeaconHandlerTest` and removed instantation of it in other tests

## Fixed Issue(s)
changes for #6918 

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [X] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by tbenr — APPROVED** [review]
LGTM

**Comment by tbenr** [comment]
@StefanBratanov thinking about adding this in changelog too

**Comment by StefanBratanov** [comment]
> @StefanBratanov thinking about adding this in changelog too

Yes, I will add it in other PR. Forgot.

**Comment by lucassaldanha** [comment]
Oh sorry, it was approved so I set it to auto-merge... :)

**Pull request merged**
