### PR TITLE
Use external signer with interop mock start validator

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Currently, interop mode `--Xinterop-enabled=true` only uses local signing. This PR enables the interop validators with external signer if `--validators-external-signer-url http://localhost:9000` is specified. It is assumed that external signer has already loaded the interop validator keys which are also provided in `interop-keys` directory.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by rolfyone** [comment]
This looks ok to me, but I haven't tried it yet... hopefully someone can have a play...

**Comment by tbenr** [comment]
@usmansaleem I tried to find some interop keys good for web3signer, but I failed. Do you have a bunch of them to share so I can test? It would be super useful to me in future testing too, so I'll be always able to include web3signer in the mix.

**Comment by rolfyone** [comment]
can use web3signer and keymanager and then it'll have the keys..

**Comment by usmansaleem** [comment]
> @usmansaleem I tried to find some interop keys good for web3signer, but I failed. Do you have a bunch of them to share so I can test? It would be super useful to me in future testing too, so I'll be always able to include web3signer in the mix.

@tbenr 
The Teku repo already contains the interop keys https://github.com/Consensys/teku/tree/master/interop-keys . You can point the `keys` and `passwords` directly in web3signer to perform "bulk loading" i.e. :
```
eth2.keystores-path: "teku/interop-keys/keys"
eth2.keystores-passwords-path: "teku/interop-keys/passwords"
```

**Review by tbenr — APPROVED** [review]
LGTM.
thanks @usmansaleem and @rolfyone for the help to setup the interop web3signer!

**Pull request merged**
