### PR TITLE
fix blob sidecars by range integration test

### PR DESCRIPTION
**Pull request by mehdi-aouadi**
## PR Description
Fix broken `BlobSidecarsByRangeIntegrationTest`

## Fixed Issue(s)

#7617 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by StefanBratanov** [comment]
The default seems to be 30 seconds, so on regular basis it takes longer with the new trusted setup?

**Comment by mehdi-aouadi** [comment]
> The default seems to be 30 seconds, so on regular basis it takes longer with the new trusted setup?

I just pushed a change to use the default timeout :) Let's see!

**Comment by mehdi-aouadi** [comment]
@StefanBratanov the default 30s timeout looks ok

**Review by StefanBratanov — APPROVED** [review]
LGTM

**Pull request merged**
