### PR TITLE
WIP: docker content trust signing for images

### PR DESCRIPTION
**Pull request by joshuafernandes**
## PR Description
docker content trust signing for images

### CODE REVIEW

**Comment by ajsutton** [comment]
Commented on the web3signer version of this, but doesn't this break multi arch support?

**Review by ajsutton — CHANGES_REQUESTED** [review]
As discussed, it does appear this breaks multi-arch support.  Going to up the review to "request changes" while we sort this out just so no one gets carried away and merges it before then.  It can be really easy to miss the fact multi-arch was broken if you are running on intel. :)

**Comment by joshuafernandes** [comment]
> As discussed, it does appear this breaks multi-arch support. Going to up the review to "request changes" while we sort this out just so no one gets carried away and merges it before then. It can be really easy to miss the fact multi-arch was broken if you are running on intel. :)

Yep, I'll ping once I have this sorted either with arch in the tag or equivalent. Have set the title to WIP

**Comment by ajsutton** [comment]
I'm going to close this one for now just to keep things tidy but feel free to reopen if you get back to looking at this.

**Pull request closed without merging**
