### PR TITLE
Remove JSON deserializer for SszBitvector

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Remove deserialiser definition for SszBitvector.

It's not schema aware so is trying to guess the length based on the data which isn't reliable. Wasn't actually used in production anymore.
Also updated the remove validator AT to check that sync committee messages/contributions are published successfully.

## Fixed Issue(s)
Alternative to #5544 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by jtraglia** [comment]
So from a testing perspective, I would like a way to deserialize this type. Without this, we are unable to deserialize a BeaconState value, since `justification_bits` is a bitvector. How would the receiver of this deserialize it?

```
JsonProviderPropertyTest > roundTripBeaconState FAILED
    com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `tech.pegasys.teku.infrastructure.ssz.collections.SszBitvector` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
     at [Source: (StringReader); line: 1, column: 6124181] (through reference chain: tech.pegasys.teku.api.schema.phase0.BeaconStatePhase0["justification_bits"])
        at app//com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at app//com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904)
        at app//com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
        at app//com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349)
        at app//com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:274)
        at app//com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at app//com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:563)
        at app//com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:438)
        at app//com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at app//com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at app//com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at app//com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3629)
        at app//com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3597)
        at app//tech.pegasys.teku.provider.JsonProvider.jsonToObject(JsonProvider.java:112)
        at app//tech.pegasys.teku.provider.JsonProviderPropertyTest.roundTripBeaconState(JsonProviderPropertyTest.java:398)
```

(From an uncommitted property test)

PS: My Thai friends [would find this PR hilarious](https://www.quora.com/Thailand-What-is-the-significance-of-the-numbers-555-for-Thai-people).

**Comment by ajsutton** [comment]
> How would the receiver of this deserialize it?

If you have JSON for a `BeaconState` you can get a `DeserializableTypeDefinition` from the SSZ schema and use that to parse the whole object.  https://github.com/ConsenSys/teku/pull/5555/files#diff-bea1d5d6503cbeef0f20408ed2ffb76ff5189d9759b9e82d756df66426efeadf was switched to use the new type definitions parsing.

Specifically for a Bitvector it's actually SSZ encoded then converted to hex so you can deserialise by parsing the hex (`Bytes.fromHexString`) and then parsing with `SszBitvector.sszDeserialize.  `JsonProviderTest.bitVectorShouldSerializeAndDeserialize` was updated to use this approach to confirm the serialisation is correct.

**Comment by ajsutton** [comment]
Looks like a missed a usage in the ATs though.

**Comment by jtraglia** [comment]
> > How would the receiver of this deserialize it?
> 
> If you have JSON for a `BeaconState` you can get a `DeserializableTypeDefinition` from the SSZ schema and use that to parse the whole object.

Ah I understand now. Thank you. In that case, this looks good.

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
