### PR TITLE
CI workflow: continue with test jobs even if spotless failed

### PR DESCRIPTION
**Pull request by Nashatyrev**
## PR Description

When working on a PR I often use CI as background test runner. I.e. pushing one or couple commits to PR to see what might get broken. And it's annoying to periodically see that tests were not run because of `spotless` job failure

This PR just makes all jobs not dependent on `spotless` job. So even if `spotless` fails other jobs proceed. If the `spotless` fails the overall build still marked as failed. 

Here `spotless` failed, the commit is immediately marked as failed. However other jobs are not aborted
изображение
изображение

Here are screens when build completed:
изображение
изображение

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by Nashatyrev** [comment]
With the `docker` job dependency it doesn't work though :/

изображение

**Comment by ajsutton** [comment]
> With the `docker` job dependency it doesn't work though :/

Yeah you don't need `docker` to depend on `spotless` just all the steps that start with `publish` (`publish`, `publishCloudsmith`, `publishDocker`, `publishAPISpec` etc).  They're also the ones that currently depend on a big list of things (`unitTests`, `acceptanceTests` etc).

**Comment by Nashatyrev** [comment]
> Yeah you don't need docker to depend on spotless just all the steps that start with publish (publish, publishCloudsmith, publishDocker, publishAPISpec etc)

That worked 👍

**Review by ajsutton — APPROVED** [review]
LGTM.

**Pull request merged**
