### PR TITLE
Reject negative values in byte deserializer

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

Due to recent changes to the byte type definition, negative integer values (`"0x80000000"` - `"0xffffffff"`) are allowed.

I do not believe this should be allowed.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by jtraglia** [comment]
Just to mention, prior to this PR the negative value would be cast to a byte and lose to upper bits.

For example, `0x89312050` would result in a value of `0x50`.

**Comment by jtraglia** [comment]
Just to mention, prior to this PR the negative value would be cast to a byte and lose the upper bits.

For example, `0x89312050` would result in a value of `0x50`.

**Comment by jtraglia** [comment]
Also worth mentioning, I don't think that `Integer.parseUnsignedInt` behaves the way the author of this intended. `Integer.parseUnsignedInt("ffffffff", 16)` and `Integer.parseUnsignedInt("4294967295", 10)` will result in `-1`. I will update `UInt8TypeDefinition` to fix the same problem.

**Comment by ajsutton** [comment]
Thanks. Changes look good - I've pushed up a commit that changes the tests a bit. The property tests would pass even if a valid value failed to parse which was happening for a lot of hex encoded values because they weren't string quoted. Also changed the `RestApiRequestTest` to hard code the serialised forms instead of generating them at @rolfyone 's suggestion so we don't have the problem of it encoding them incorrectly again in the future.

Can you double check my changes and if you're happy with them I'll merge please? Given I messed this up just yesterday a second pair of eyes would be good. :)

**Comment by jtraglia** [comment]
Yes, your changes look good to me. Thanks for revising those tests. I also fixed a small nit in something else.

**Comment by jtraglia** [comment]
Actually one second. Just noticed something.

**Comment by jtraglia** [comment]
Okay I'm done now. Ready to merge.

**Review by ajsutton — APPROVED** [review]

**Pull request merged**
